**Molecular glue and PROTACs LLM prediction vs. ground truth for the 1st run**

# Porcess PROTACs Extracted Data

In [1]:
import pandas as pd
import os
import glob


base_dir = "/Users/yaochenr/project/molecular_glue_extractor/output/results"
batches = {
    "batch_1": "260401_1036",
    "batch_2": "260401_1116",
    "batch_3": "260401_1420",
    "batch_4": "260401_1448",
    "batch_5": "260401_1531",
    "batch_6": "260401_1629",
    "batch_7": "260401_1714",
    "batch_8": "260401_1745",
    "batch_9": "260401_2101",
    "batch_10": "260401_2131",
    "batch_11": "260401_2157",
    "batch_12": "260401_2247",
    "batch_13": "260401_2322",
    "batch_14": "260401_2346",
}

dfs = []

for batch_name, folder in batches.items():
    path = os.path.join(base_dir, folder, "data_processed.csv")
    df_protacs = pd.read_csv(path)
    dfs.append(df_protacs)
    print(f"{batch_name} ({folder}): {len(df_protacs)} rows")

merged_protacs = pd.concat(dfs, ignore_index=True)
if "source" in merged_protacs.columns:
    merged_protacs = merged_protacs.drop(columns=["source"])
print(f"\nTotal rows: {len(merged_protacs)}")
print(f"Unique DOIs: {merged_protacs['DOI'].nunique()}")
print(f"Unknown DOIs: {(merged_protacs['DOI'] == 'Unknown').sum()}")
print(f"Columns: {list(merged_protacs.columns)}")
merged_protacs.head()

batch_1 (260401_1036): 42 rows
batch_2 (260401_1116): 48 rows
batch_3 (260401_1420): 60 rows
batch_4 (260401_1448): 130 rows
batch_5 (260401_1531): 106 rows
batch_6 (260401_1629): 25 rows
batch_7 (260401_1714): 43 rows
batch_8 (260401_1745): 18 rows
batch_9 (260401_2101): 114 rows
batch_10 (260401_2131): 45 rows
batch_11 (260401_2157): 34 rows
batch_12 (260401_2247): 36 rows
batch_13 (260401_2322): 47 rows
batch_14 (260401_2346): 77 rows

Total rows: 825
Unique DOIs: 121
Unknown DOIs: 0
Columns: ['DOI', 'Compound_Name', 'IUPAC_Name', 'SMILES', 'Degradation_Target', 'Recruiter', 'Assay', 'Cell_Line', 'DC50', 'DC50_units', 'DC50_h', 'Dmax', 'Dmax_h', 'Dmax_conc']

,DOI,Compound_Name,IUPAC_Name,SMILES,Degradation_Target,Recruiter,Assay,Cell_Line,DC50,DC50_units,DC50_h,Dmax,Dmax_h,Dmax_conc
0,10.1038/s42003-020-0868-6,4,(S)-N-((S)-1-(1-(2-(4-(2-((6-(tert-Butylsulfon...,NaN,RIPK2,IAP,Simple Western immunoassay (capillary-based),human PBMCs,12.6,nM,24,69.2±11.5,24,NaN
1,10.1038/s42003-020-0868-6,6,"5-(4-(3-((6-(tert-Butylsulfonyl)-4-((4,5-dimet...",NaN,RIPK2,IAP,Simple Western immunoassay (capillary-based),human PBMCs,0.4,nM,24,94.3±3.2,24,NaN
2,10.1038/s42003-020-0868-6,2,(S)-7-(2-(2-(2-(2-((4-(benzo[d]thiazol-5-ylami...,NaN,RIPK2,IAP,Capillary-based immunoassay (Simple Western),THP-1,0.4,nM,18,NaN,NaN,NaN
3,10.1038/s42003-020-0868-6,1,NaN,NaN,RIPK2,VHL,Capillary-based immunoassay (Simple Western),THP-1,2.0,nM,18,NaN,NaN,NaN
4,10.1038/s42003-020-0868-6,3,(S)-14-((4-(Benzo[d]thiazol-5-ylamino)-6-(tert...,NaN,RIPK2,cereblon,Capillary-based immunoassay (Simple Western),THP-1,2.5,nM,18,NaN,NaN,NaN

In [14]:
merged_protacs.shape

(825, 14)

In [3]:
data_dir = "/Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_1st"
os.makedirs(data_dir, exist_ok=True)
output_path = os.path.join(data_dir, "260502_merged_protac_data_processed_1st.csv")
merged_protacs.to_csv(output_path, index=False)
print(f"Saved merged data to: {output_path}")
print(f"Shape: {merged_protacs.shape}")

Saved merged data to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_1st/260502_merged_protac_data_processed_1st.csv
Shape: (825, 14)

# Process Molecular Glues Extracted Data

In [13]:
import pandas as pd
import os
import glob


base_dir = "/Users/yaochenr/project/molecular_glue_extractor/output/results"
batches = {
    "batch_1": "260304_0952",
    "batch_2": "260304_1043",
    "batch_3": "260304_1127",
    "batch_4": "260304_1240",
    "batch_5": "260304_1304",
}

dfs = []

for batch_name, folder in batches.items():
    path = os.path.join(base_dir, folder, "data_processed.csv")
    df = pd.read_csv(path)
    dfs.append(df)
    print(f"{batch_name} ({folder}): {len(df)} rows")

active_prompting_dir = os.path.join(
    base_dir, "active_prompting_batch_260131_2330/round_2/batch_results"
)
ap_files = sorted(glob.glob(os.path.join(active_prompting_dir, "*/data_processed.csv")))
for path in ap_files:
    df = pd.read_csv(path)
    dfs.append(df)
    paper_name = os.path.basename(os.path.dirname(path))
    print(f"active_prompting ({paper_name}): {len(df)} rows")

held_out_path = os.path.join(base_dir, "260201_0042", "data_processed.csv")
df_held_out = pd.read_csv(held_out_path)
dfs.append(df_held_out)
print(f"held_out_test_set (260201_0042): {len(df_held_out)} rows")

merged_glues = pd.concat(dfs, ignore_index=True)
if "source" in merged_glues.columns:
    merged_glues = merged_glues.drop(columns=["source"])
print(f"\nTotal rows: {len(merged_glues)}")
print(f"Columns: {list(merged_glues.columns)}")
merged_glues.head()

batch_1 (260304_0952): 81 rows
batch_2 (260304_1043): 81 rows
batch_3 (260304_1127): 18 rows
batch_4 (260304_1240): 29 rows
batch_5 (260304_1304): 28 rows
active_prompting (paper_10.1016_j.ejmech.2024.116904): 8 rows
active_prompting (paper_10.1021_acs.jmedchem.0c01313): 10 rows
active_prompting (paper_10.1021_acs.jmedchem.1c02175): 22 rows
active_prompting (paper_10.1021_jacs.3c08307): 2 rows
active_prompting (paper_10.1038_s41467-025-58431-z): 37 rows
active_prompting (paper_10.1126_science.adk4422): 6 rows
held_out_test_set (260201_0042): 15 rows

Total rows: 337
Columns: ['DOI', 'Compound_Name', 'IUPAC_Name', 'SMILES', 'Degradation_Target', 'Recruiter', 'Assay', 'Cell_Line', 'DC50', 'DC50_units', 'DC50_h', 'Dmax', 'Dmax_h', 'Dmax_conc']

,DOI,Compound_Name,IUPAC_Name,SMILES,Degradation_Target,Recruiter,Assay,Cell_Line,DC50,DC50_units,DC50_h,Dmax,Dmax_h,Dmax_conc
0,10.1021/acs.jmedchem.3c00851,43h,"4-[4-[[[2-[(9S)-7-(4-Chlorophenyl)-4,5,13-trim...",O=C(NC(CC1)C(NC1=O)=O)C2=CC=C(N3CCC(CNC(C[C@@H...,BRD4,CRBN,Western blot densitometry,MOLT4,4.7,nM,24 h,>99,24 h,NaN
1,10.1021/acs.jmedchem.3c00851,44h,"4-[4-[[[2-[(9S)-7-(4-Chlorophenyl)-4,5,13-trim...",O=C(NC(CC1)C(NC1=O)=O)C2=CC=C(N3CCC(CNC(C[C@@H...,BRD4,CRBN,Western blot densitometry,MOLT4,0.59,nM,24 h,>99,24 h,NaN
2,10.1021/acs.jmedchem.3c00851,51,"N-(2,6-Dioxo-3-piperidyl)-4-[[2-[[8-[4-[[7-(hy...",O=C(NC(CC1)C(NC1=O)=O)C2=CC=C(NCC(NCCCCCCCC(NC...,HDAC6,CRBN,Western blot densitometry,MM.1S,5.8,nM,24 h,NaN,NaN,NaN
3,10.1038/s41589-023-01409-z,DS64,"(R)-2-((6-((4,5-difluoro-1H-benzo[d]imidazol-2...",NaN,cyclin K,DDB1–CUL4–RBX1,HEK293T cyclin K–eGFP reporter assay,HEK293T–Cas9,62,nM,5,NaN,NaN,NaN
4,10.1038/s41589-023-01409-z,DS18,"N-((5,6-dichloro-1H-benzo[d]imidazol-2-yl)meth...",NaN,cyclin K,DDB1–CUL4–RBX1,HEK293T cyclin K–eGFP reporter assay,HEK293T–Cas9,13,nM,5,NaN,NaN,NaN

# Processing Functions

In [ ]:
import requests
import time
from urllib.parse import quote
import pubchempy as pcp


OPSIN_BASE = "https://www.ebi.ac.uk/opsin/ws"
_DASH_CHARS = "‐‑‒–—―−﹣－"
_DASH_TRANS = str.maketrans({c: "-" for c in _DASH_CHARS})


def _normalize_dashes(s):
    if not isinstance(s, str):
        return s
    return s.translate(_DASH_TRANS)


PUBCHEM_BLOCKLIST = {
    "Mei", "Po", "Le",
    "LC-4", "LC-6",
    "D10", "D12", "D15",
    "A13", "13b",
    "SC5", "SC7", "SC10",
    "DBt-10",
    "PS-6",
    "MD9",
    "Cpd 1",
}


def remove_empty_dc50_dmax(df):
    before = len(df)
    cleaned = df.dropna(subset=["DC50", "Dmax"], how="all")
    cleaned = cleaned[~(
        cleaned["DC50"].astype(str).str.strip().isin(["", "nan"])
        & cleaned["Dmax"].astype(str).str.strip().isin(["", "nan"])
    )]
    cleaned = cleaned.reset_index(drop=True)
    after = len(cleaned)
    print(f"Removed {before - after} rows where both DC50 and Dmax are empty")
    print(f"Shape: {before} -> {after}")
    return cleaned


def add_inchikey_opsin(df, sleep_sec=0.1):
    df = df.copy()
    df["Standard_InChIKey"] = pd.NA
    df["Standard_InChIKey_Source"] = pd.NA
    if "SMILES_Source" not in df.columns:
        df["SMILES_Source"] = pd.NA

    has_smiles = df["SMILES"].notna() & (df["SMILES"].astype(str).str.strip() != "")
    df.loc[has_smiles, "SMILES_Source"] = "PAPER"
    print(f"Rows with SMILES from paper: {has_smiles.sum()}")

    success, fail, skip = 0, 0, 0
    failed_rows = []

    for idx, row in df.iterrows():
        iupac = row["IUPAC_Name"]
        if pd.isna(iupac) or str(iupac).strip() == "":
            skip += 1
            continue

        url = f"{OPSIN_BASE}/{quote(str(iupac).strip(), safe='')}.json"
        try:
            resp = requests.get(url, timeout=30)
            if resp.status_code == 200:
                data = resp.json()
                inchikey = data.get("stdinchikey")
                smiles = data.get("smiles")
                if inchikey:
                    df.at[idx, "Standard_InChIKey"] = inchikey
                    df.at[idx, "Standard_InChIKey_Source"] = "OPSIN"
                if not has_smiles[idx] and smiles:
                    df.at[idx, "SMILES"] = smiles
                    df.at[idx, "SMILES_Source"] = "OPSIN"
                success += 1
            else:
                failed_rows.append({"row": idx, "status": resp.status_code, "DOI": row["DOI"], "Compound_Name": row["Compound_Name"], "IUPAC_Name": str(iupac)[:100]})
                fail += 1
        except Exception as e:
            failed_rows.append({"row": idx, "error": str(e), "DOI": row["DOI"], "Compound_Name": row["Compound_Name"], "IUPAC_Name": str(iupac)[:100]})
            fail += 1

        if (idx + 1) % 50 == 0:
            print(f"Processed {idx + 1}/{len(df)} rows...")
        time.sleep(sleep_sec)

    cols = list(df.columns)
    smiles_idx = cols.index("SMILES")
    cols.remove("SMILES_Source")
    cols.insert(smiles_idx + 1, "SMILES_Source")
    df = df[cols]

    print(f"\nDone! Success: {success}, Failed: {fail}, Skipped (no IUPAC): {skip}")
    print(f"Standard_InChIKey filled: {df['Standard_InChIKey'].notna().sum()}")
    print(f"SMILES from PAPER: {(df['SMILES_Source'] == 'PAPER').sum()}")
    print(f"SMILES from OPSIN: {(df['SMILES_Source'] == 'OPSIN').sum()}")
    print(f"SMILES still missing: {df['SMILES'].isna().sum()}")
    if failed_rows:
        print(f"\n--- Failed rows ---")
        for fr in failed_rows:
            print(fr)
    return df


def pubchem_search(df, sleep_sec=0.3, blocklist=None, min_name_length=3):
    """Fill Standard_InChIKey (and IUPAC_Name / SMILES if missing) via PubChem.
    """
    df = df.copy()
    if blocklist is None:
        blocklist = PUBCHEM_BLOCKLIST

    def has_value(v):
        return pd.notna(v) and str(v).strip() != "" and str(v).strip().lower() != "nan"

    def is_numeric_name(s):
        return s.replace(".", "").replace("-", "").isdigit()

    def cname_usable(c):
        if not c:
            return False
        if c in blocklist or _normalize_dashes(c) in blocklist:
            return False
        if is_numeric_name(c):
            return False
        if len(c) < min_name_length:
            return False
        return True

    def search_name_with_synonym(raw_query):
        query = _normalize_dashes(raw_query).strip()
        if not query:
            return None, "empty after normalization"
        try:
            compounds = pcp.get_compounds(query, "name")
            if not compounds:
                return None, "0 results"
            top = compounds[0]
            syn_url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/{top.cid}/synonyms/JSON"
            syn_resp = requests.get(syn_url, timeout=30)
            if syn_resp.status_code != 200:
                return None, f"synonyms HTTP {syn_resp.status_code} (CID={top.cid})"
            syns = syn_resp.json()["InformationList"]["Information"][0]["Synonym"]
            q_cmp = query.lower()
            if not any(_normalize_dashes(s).lower() == q_cmp for s in syns):
                return None, f"not in synonyms (CID={top.cid})"
            return {"cid": top.cid, "iupac_name": top.iupac_name,
                    "smiles": top.smiles, "inchikey": top.inchikey}, "ok"
        except Exception as e:
            return None, f"error: {e}"

    def search_smiles(query):
        try:
            compounds = pcp.get_compounds(query, "smiles")
            if not compounds:
                return None, "0 results"
            top = compounds[0]
            return {"cid": top.cid, "iupac_name": top.iupac_name,
                    "smiles": top.smiles, "inchikey": top.inchikey}, "ok"
        except Exception as e:
            return None, f"error: {e}"

    def chem_search(iupac, smiles):
        if iupac:
            r, reason = search_name_with_synonym(iupac)
            time.sleep(sleep_sec)
            if r:
                return r, "IUPAC", reason
            iupac_reason = reason
        else:
            iupac_reason = "no IUPAC"
        if smiles:
            r, reason = search_smiles(smiles)
            time.sleep(sleep_sec)
            if r:
                return r, "SMILES", reason
            smiles_reason = reason
        else:
            smiles_reason = "no SMILES"
        return None, None, f"IUPAC={iupac_reason}, SMILES={smiles_reason}"

    for col in ("IUPAC_Name_Source", "Standard_InChIKey",
                "Standard_InChIKey_Source", "SMILES_Source"):
        if col not in df.columns:
            df[col] = pd.NA

    needs_key = df["Standard_InChIKey"].isna() | (df["Standard_InChIKey"].astype(str).str.strip() == "")
    to_search = df[needs_key].index

    queries = {}
    for idx in to_search:
        cname = str(df.at[idx, "Compound_Name"]).strip() if has_value(df.at[idx, "Compound_Name"]) else ""
        iupac = str(df.at[idx, "IUPAC_Name"]).strip()    if has_value(df.at[idx, "IUPAC_Name"])    else ""
        smi   = str(df.at[idx, "SMILES"]).strip()        if has_value(df.at[idx, "SMILES"])        else ""
        queries.setdefault((cname, iupac, smi), []).append(idx)

    print(f"Rows missing Standard_InChIKey: {len(to_search)} ({len(queries)} unique (cname, iupac, smiles) triples)")

    def short(s, n=40):
        return (s[:n] + "...") if s and len(s) > n else s

    cache = {}
    for (cname, iupac, smi), idxs in queries.items():
        usable_c = cname_usable(cname)
        has_chem = bool(iupac) or bool(smi)
        cs = short(cname) if cname else "(no cname)"

        result, method, reason = None, None, ""

        if usable_c and not has_chem:
            r, reason_c = search_name_with_synonym(cname)
            time.sleep(sleep_sec)
            if r:
                result, method, reason = r, "cname", reason_c
            else:
                reason = f"cname={reason_c}"
        elif usable_c and has_chem:
            r, reason_c = search_name_with_synonym(cname)
            time.sleep(sleep_sec)
            if r:
                result, method, reason = r, "cname", reason_c
            else:
                result, method, reason_chem = chem_search(iupac, smi)
                reason = f"cname={reason_c}; {reason_chem}" if not result else f"after cname miss: {reason_chem}"
        elif not usable_c and has_chem:
            result, method, reason_chem = chem_search(iupac, smi)
            reason = f"cname unusable; {reason_chem}"
        else:
            reason = "skip: no usable name and no IUPAC/SMILES"

        cache[(cname, iupac, smi)] = result

        if result:
            print(f"  MATCH '{cs}' via {method}: CID={result['cid']}, InChIKey={result['inchikey']}")
        else:
            print(f"  MISS  '{cs}': {reason}")

    filled_key = filled_iupac = filled_smi = 0
    for (cname, iupac, smi), idxs in queries.items():
        result = cache[(cname, iupac, smi)]
        if result is None:
            continue
        for idx in idxs:
            if result["inchikey"]:
                df.at[idx, "Standard_InChIKey"] = result["inchikey"]
                df.at[idx, "Standard_InChIKey_Source"] = "PUBCHEM"
                filled_key += 1
            if not has_value(df.at[idx, "IUPAC_Name"]) and result.get("iupac_name"):
                df.at[idx, "IUPAC_Name"] = result["iupac_name"]
                df.at[idx, "IUPAC_Name_Source"] = "PUBCHEM"
                filled_iupac += 1
            if not has_value(df.at[idx, "SMILES"]) and result.get("smiles"):
                df.at[idx, "SMILES"] = result["smiles"]
                df.at[idx, "SMILES_Source"] = "PUBCHEM"
                filled_smi += 1

    matched = sum(1 for v in cache.values() if v is not None)
    print(f"\n--- PubChem Results ---")
    print(f"Matched triples: {matched}/{len(queries)}")
    print(f"Standard_InChIKey filled: {filled_key}")
    print(f"IUPAC_Name filled: {filled_iupac}")
    print(f"SMILES filled: {filled_smi}")
    print(f"Standard_InChIKey still missing: {(df['Standard_InChIKey'].isna() | (df['Standard_InChIKey'].astype(str).str.strip() == '')).sum()}")
    return df

def add_connectivity_key(df):
    if 'Standard_InChIKey' in df.columns:
        df['Connectivity_Key'] = df['Standard_InChIKey'].str[:14]
    return df

# PROTACs

### Remove rows where DC50 & Dmax are both empty

In [5]:
merged_cleaned_protac = remove_empty_dc50_dmax(merged_protacs)

Removed 111 rows where both DC50 and Dmax are empty
Shape: 825 -> 714

In [ ]:
output_merged = os.path.join(data_dir, "260502_merged_protac_data_processed_cleaned_1st.csv")
merged_cleaned_protac.to_csv(output_merged, index=False)
print(f"Saved cleaned merged data to: {output_merged}")
print(f"Shape: {merged_cleaned_protac.shape}")

Saved cleaned merged data to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_1st/260502_merged_protac_data_processed_cleaned_1st.csv
Shape: (714, 14)

### Add Standard InChIKey via OPSIN

In [7]:
merged_cleaned_protac = add_inchikey_opsin(merged_cleaned_protac)

Rows with SMILES from paper: 117
Processed 50/714 rows...
Processed 150/714 rows...
Processed 250/714 rows...
Processed 300/714 rows...
Processed 350/714 rows...
Processed 500/714 rows...
Processed 700/714 rows...

Done! Success: 385, Failed: 100, Skipped (no IUPAC): 229
Standard_InChIKey filled: 385
SMILES from PAPER: 117
SMILES from OPSIN: 289
SMILES still missing: 308

--- Failed rows ---
{'row': 2, 'status': 404, 'DOI': '10.1038/s42003-020-0868-6', 'Compound_Name': '2', 'IUPAC_Name': '(S)-7-(2-(2-(2-(2-((4-(benzo[d]thiazol-5-ylamino)-6-(tert-butylsulfonyl)quinolin-7-yl)oxy)ethoxy)eth'}
{'row': 48, 'status': 404, 'DOI': '10.1038/s41467-018-08027-7', 'Compound_Name': 'SJF-8240', 'IUPAC_Name': 'N-(3-Fluoro-4-((7-(3-(3-(3-(((S)-1-((2S,4R)-4-hydroxy-2-((4-(4-methylthiazol-5-yl)benzyl)carbamoyl)-'}
{'row': 113, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00771', 'Compound_Name': 'NU223612', 'IUPAC_Name': '(2R)-N-(4-((1-(3-(2-(2-((2-(2,6-Dioxopiperidin-3-yl)-1,3-dioxoisoindolin-4-Yl)amino)ethoxy)ethoxy)pr'}
{'row': 114, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00771', 'Compound_Name': 'NU223612', 'IUPAC_Name': '(2R)-N-(4-((1-(3-(2-(2-((2-(2,6-Dioxopiperidin-3-yl)-1,3-dioxoisoindolin-4-Yl)amino)ethoxy)ethoxy)pr'}
{'row': 119, 'status': 404, 'DOI': '10.1021/jacs.2c05499', 'Compound_Name': 'XL01126', 'IUPAC_Name': '(2S,4R)-1-((R)-3-((((1R,4R)-4-((4-(4-((5-Chloro-4-(methylamino)pyrimidin-2-yl)amino)-3-methoxybenzoy'}
{'row': 120, 'status': 404, 'DOI': '10.1021/jacs.2c05499', 'Compound_Name': 'XL01126', 'IUPAC_Name': '(2S,4R)-1-((R)-3-((((1R,4R)-4-((4-(4-((5-Chloro-4-(methylamino)pyrimidin-2-yl)amino)-3-methoxybenzoy'}
{'row': 123, 'status': 404, 'DOI': '10.1021/jacs.2c05499', 'Compound_Name': 'XL01126', 'IUPAC_Name': '(2S,4R)-1-((R)-3-((((1R,4R)-4-((4-(4-((5-Chloro-4-(methylamino)pyrimidin-2-yl)amino)-3-methoxybenzoy'}
{'row': 124, 'status': 404, 'DOI': '10.1021/jacs.2c05499', 'Compound_Name': 'XL01126', 'IUPAC_Name': '(2S,4R)-1-((R)-3-((((1R,4R)-4-((4-(4-((5-Chloro-4-(methylamino)pyrimidin-2-yl)amino)-3-methoxybenzoy'}
{'row': 125, 'status': 404, 'DOI': '10.1021/jacs.2c05499', 'Compound_Name': 'XL01126', 'IUPAC_Name': '(2S,4R)-1-((R)-3-((((1R,4R)-4-((4-(4-((5-Chloro-4-(methylamino)pyrimidin-2-yl)amino)-3-methoxybenzoy'}
{'row': 126, 'status': 404, 'DOI': '10.1021/jacs.2c05499', 'Compound_Name': 'XL01126', 'IUPAC_Name': '(2S,4R)-1-((R)-3-((((1R,4R)-4-((4-(4-((5-Chloro-4-(methylamino)pyrimidin-2-yl)amino)-3-methoxybenzoy'}
{'row': 158, 'status': 404, 'DOI': '10.1038/s41467-022-33430-6', 'Compound_Name': '22', 'IUPAC_Name': '(2S,4R)-N-(2-(2-(2-(2-(2-(4-(4-bromo-7-cyclopentyl-5-oxo-5,7-dihydrobenzo[4,5]imidazo[1,2 a]quinazol'}
{'row': 159, 'status': 404, 'DOI': '10.1038/s41467-022-33430-6', 'Compound_Name': '22', 'IUPAC_Name': '(2S,4R)-N-(2-(2-(2-(2-(2-(4-(4-bromo-7-cyclopentyl-5-oxo-5,7-dihydrobenzo[4,5]imidazo[1,2 a]quinazol'}
{'row': 160, 'status': 404, 'DOI': '10.1038/s41467-022-33430-6', 'Compound_Name': '22', 'IUPAC_Name': '(2S,4R)-N-(2-(2-(2-(2-(2-(4-(4-bromo-7-cyclopentyl-5-oxo-5,7-dihydrobenzo[4,5]imidazo[1,2 a]quinazol'}
{'row': 161, 'status': 404, 'DOI': '10.1038/s41467-022-33430-6', 'Compound_Name': '22', 'IUPAC_Name': '(2S,4R)-N-(2-(2-(2-(2-(2-(4-(4-bromo-7-cyclopentyl-5-oxo-5,7-dihydrobenzo[4,5]imidazo[1,2 a]quinazol'}
{'row': 239, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6c', 'IUPAC_Name': '4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)-N-(2-(2,6-dioxopip'}
{'row': 240, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6c', 'IUPAC_Name': '4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)-N-(2-(2,6-dioxopip'}
{'row': 241, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6d', 'IUPAC_Name': '2-(4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)piperazin-1-yl)-'}
{'row': 242, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6d', 'IUPAC_Name': '2-(4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)piperazin-1-yl)-'}
{'row': 243, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6e', 'IUPAC_Name': '3-(4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)piperazin-1-yl)-'}
{'row': 244, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6e', 'IUPAC_Name': '3-(4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)piperazin-1-yl)-'}
{'row': 245, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7b', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((E)-3-(2-(2,6-dioxopiperidin-'}
{'row': 246, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7b', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((E)-3-(2-(2,6-dioxopiperidin-'}
{'row': 247, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7e', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-(2-((2-(2,6-dioxopiperidin-3-y'}
{'row': 248, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7e', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-(2-((2-(2,6-dioxopiperidin-3-y'}
{'row': 249, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7f', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}
{'row': 250, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7f', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}
{'row': 251, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '8a', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}
{'row': 252, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '8a', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}
{'row': 253, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '8b', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}
{'row': 254, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '8b', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}
{'row': 272, 'status': 404, 'DOI': '10.1016/j.apsb.2020.11.022', 'Compound_Name': '11a', 'IUPAC_Name': 'N,N-(((Oxybis(ethane-2,1-diyl))bis(oxy))bis(ethane-2,1-diyl))bis(2-(4-(2-(4-(tert-butyl)-2-ethoxyphe'}
{'row': 301, 'status': 404, 'DOI': '10.1021/acs.jmedchem.1c02179', 'Compound_Name': '10', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(2-((4-((2-Aminophenyl)carbamoyl)phenyl)amino)-2-oxoethoxy)ethoxy)acetamido)-3,3'}
{'row': 302, 'status': 404, 'DOI': '10.1021/acs.jmedchem.1c02179', 'Compound_Name': '10', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(2-((4-((2-Aminophenyl)carbamoyl)phenyl)amino)-2-oxoethoxy)ethoxy)acetamido)-3,3'}
{'row': 303, 'status': 404, 'DOI': '10.1021/acs.jmedchem.1c02179', 'Compound_Name': '10', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(2-((4-((2-Aminophenyl)carbamoyl)phenyl)amino)-2-oxoethoxy)ethoxy)acetamido)-3,3'}
{'row': 358, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15a', 'IUPAC_Name': '(2R,3R,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 359, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15a', 'IUPAC_Name': '(2R,3R,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 360, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15a', 'IUPAC_Name': '(2R,3R,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 361, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15b', 'IUPAC_Name': '(2R,3S,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 362, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15b', 'IUPAC_Name': '(2R,3S,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 363, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15b', 'IUPAC_Name': '(2R,3S,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 364, 'status': 404, 'DOI': '10.1021/acschembio.5b00216', 'Compound_Name': 'MZ1', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]tria'}
{'row': 365, 'status': 404, 'DOI': '10.1021/acschembio.5b00216', 'Compound_Name': 'MZ2', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(tert-butyl)-20-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]tria'}
{'row': 367, 'status': 404, 'DOI': '10.1021/acschembio.5b00216', 'Compound_Name': 'MZ1', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]tria'}
{'row': 406, 'status': 404, 'DOI': '10.1021/acs.jmedchem.1c01496', 'Compound_Name': 'OMZ1', 'IUPAC_Name': '(S)-13-((2S,4R)-4-Hydroxy-2-((4-(4-methylthiazol-5-yl)benzyl)carbamoyl)pyrrolidine-1-carbonyl)-15,15'}
{'row': 407, 'status': 404, 'DOI': '10.1021/acs.jmedchem.1c01496', 'Compound_Name': 'OMZ1', 'IUPAC_Name': '(S)-13-((2S,4R)-4-Hydroxy-2-((4-(4-methylthiazol-5-yl)benzyl)carbamoyl)pyrrolidine-1-carbonyl)-15,15'}
{'row': 408, 'status': 404, 'DOI': '10.1021/acs.jmedchem.1c01496', 'Compound_Name': 'OMZ1', 'IUPAC_Name': '(S)-13-((2S,4R)-4-Hydroxy-2-((4-(4-methylthiazol-5-yl)benzyl)carbamoyl)pyrrolidine-1-carbonyl)-15,15'}
{'row': 428, 'status': 404, 'DOI': '10.1038/s41591-019-0668-z', 'Compound_Name': 'DT2216', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(7-(4-((R)-3-((4-(N-(4-(4-((4 -chloro-4,4-dimethyl-3,4,5,6-tetrahydro-[1,1 -bipheny'}
{'row': 536, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 537, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 538, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 539, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 540, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 541, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 542, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 544, 'status': 404, 'DOI': '10.1007/s13238-018-0602-z', 'Compound_Name': 'NP8', 'IUPAC_Name': '4-((1-(4-(1-(2-(2-(2-((2-(2,6-dioxopiperidin-3-yl)-1,3-dioxoisoindolin-4-yl)amino)eth oxy)etoxy)ethy'}
{'row': 568, 'status': 404, 'DOI': '10.1021/jacs.9b13907', 'Compound_Name': 'NC-1', 'IUPAC_Name': '4-(((E)-19-((S)-3-(4-amino-3-(4-phenoxyphenyl)-1H-pyrazolo[3,4-d]pyrimidin-1-yl)-19-oxo-3,6,9,12-tet'}
{'row': 575, 'status': 404, 'DOI': '10.1021/jacs.9b13907', 'Compound_Name': 'NC-1', 'IUPAC_Name': '4-(((E)-19-((S)-3-(4-amino-3-(4-phenoxyphenyl)-1H-pyrazolo[3,4-d]pyrimidin-1-yl)-19-oxo-3,6,9,12-tet'}
{'row': 664, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 665, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 666, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 667, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 668, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 669, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 670, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 671, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 672, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 673, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 674, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 675, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 676, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 677, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 678, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 679, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 680, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 681, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 682, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 683, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 684, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 685, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 686, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 687, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 688, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 689, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 690, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 691, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 692, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 693, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 694, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 695, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 696, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 697, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 698, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 699, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 700, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}

In [8]:
output_path = os.path.join(data_dir, "260502_merged_protac_data_processed_cleaned_inchikey_1st.csv")
merged_cleaned_protac.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_protac.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_1st/260502_merged_protac_data_processed_cleaned_inchikey_1st.csv
Shape: (714, 17)

### PubChem search

In [9]:
merged_cleaned_protac = pubchem_search(merged_cleaned_protac)

Rows missing Standard_InChIKey: 329 (163 unique (cname, iupac, smiles) triples)
  MISS  '2': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MISS  '1': skip: no usable name and no IUPAC/SMILES
  MATCH 'KY02111' via cname: CID=8582409, InChIKey=LXFKEVQQSKQXPR-UHFFFAOYSA-N
  MATCH 'UBX-382' via cname: CID=166545675, InChIKey=WIAKHDZSMZDZQL-UHFFFAOYSA-N
  MISS  '34 (CST651)': cname=0 results
  MATCH 'SJF-8240' via cname: CID=135175904, InChIKey=SCUZPTNDZHEHLB-ZWUDBOSPSA-N
  MISS  '2c': skip: no usable name and no IUPAC/SMILES
  MISS  'PRO-6 E': cname=0 results
  MATCH 'LC-3' via cname: CID=156885419, InChIKey=QSJKPPVXARILLJ-GYUTUTRISA-N
  MISS  'LC-4': skip: no usable name and no IUPAC/SMILES
  MATCH 'LC-5' via cname: CID=159353560, InChIKey=LHQBPRGJSOSPMT-JCKBJUPWSA-N
  MISS  'LC-6': skip: no usable name and no IUPAC/SMILES
  MISS  '5': skip: no usable name and no IUPAC/SMILES
  MISS  '7a': skip: no usable name and no IUPAC/SMILES
  MISS  '7b': skip: no usable name and no IUPAC/SMILES
  MISS  '7c': skip: no usable name and no IUPAC/SMILES
  MISS  '7d': skip: no usable name and no IUPAC/SMILES
  MISS  '7e': skip: no usable name and no IUPAC/SMILES
  MISS  '7g': skip: no usable name and no IUPAC/SMILES
  MISS  '7h': skip: no usable name and no IUPAC/SMILES
  MISS  '7i': skip: no usable name and no IUPAC/SMILES
  MISS  '7j': skip: no usable name and no IUPAC/SMILES
  MISS  '7k': skip: no usable name and no IUPAC/SMILES
  MISS  '7l': skip: no usable name and no IUPAC/SMILES
  MISS  '7m': skip: no usable name and no IUPAC/SMILES
  MISS  '7n': skip: no usable name and no IUPAC/SMILES
  MISS  '7p': skip: no usable name and no IUPAC/SMILES
  MISS  '7q': skip: no usable name and no IUPAC/SMILES
  MISS  '7s': skip: no usable name and no IUPAC/SMILES
  MISS  '7t': skip: no usable name and no IUPAC/SMILES
  MATCH 'NU223612' via cname: CID=166176927, InChIKey=PLYOHMQINGIYDN-LVMIGYEDSA-N
  MISS  '14': skip: no usable name and no IUPAC/SMILES
  MISS  'XL01134': cname=0 results
  MATCH 'XL01126' via cname: CID=165412689, InChIKey=HKSBXNVKPFTBIG-WUEKOBJSSA-N
  MISS  'A13': skip: no usable name and no IUPAC/SMILES
  MISS  '22': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MISS  '6': skip: no usable name and no IUPAC/SMILES
  MATCH 'ACBI2' via cname: CID=167738509, InChIKey=JBTHUOYYUUPUOZ-LIHPQFRDSA-N
  MATCH 'iRucaparib-AP5' via cname: CID=138857954, InChIKey=CDKSZVJXSCKNQN-UHFFFAOYSA-N
  MATCH 'iRucaparib-AP6' via cname: CID=138857977, InChIKey=YHMDCINUVWULST-UHFFFAOYSA-N
  MATCH 'iVeliparib-AP6' via cname: CID=138857963, InChIKey=XLGCZZCLPNSQNH-YMURELKOSA-N
  MISS  '7': skip: no usable name and no IUPAC/SMILES
  MISS  '11': skip: no usable name and no IUPAC/SMILES
  MATCH 'SIAIS352008' via cname: CID=155680164, InChIKey=RMADJZZMVLKVKG-UHFFFAOYSA-N
  MATCH 'SIAIS262039' via cname: CID=172872463, InChIKey=GJAQYPRTMBNTHS-UHFFFAOYSA-N
  MISS  '13a': cname=0 results
  MISS  '13b': skip: no usable name and no IUPAC/SMILES
  MISS  '13c': cname=0 results
  MISS  '13d': cname=0 results
  MATCH '6c' via SMILES: CID=168296465, InChIKey=GZGWGZGQYMUIEA-UHFFFAOYSA-N
  MATCH '6d' via SMILES: CID=168280695, InChIKey=RAQFFJNNGHFOJQ-UHFFFAOYSA-N
  MATCH '6e' via SMILES: CID=168291380, InChIKey=TXTOISHPMQZJTH-UHFFFAOYSA-N
  MATCH '7b' via SMILES: CID=168273780, InChIKey=AXXVVAVFAZXQRT-ODCIPOBUSA-N
  MATCH '7e' via SMILES: CID=168279854, InChIKey=BASKATKGOOUNTP-UHFFFAOYSA-N
  MATCH '7f' via IUPAC: CID=164887577, InChIKey=XTFJBIUTOVUAPR-UHFFFAOYSA-N
  MATCH '8a' via SMILES: CID=168290140, InChIKey=IEQQOSUYADIJKS-UHFFFAOYSA-N
  MATCH '8b' via SMILES: CID=168281662, InChIKey=BZWXDODDFPHMGW-UHFFFAOYSA-N
  MISS  '11a': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MATCH 'SIAIS361034' via cname: CID=156298253, InChIKey=FBBJZLPPVPILEL-UHFFFAOYSA-N
  MATCH '10' via SMILES: CID=166635273, InChIKey=LDFNYUSMNVVOAO-FHRXIHKVSA-N
  MISS  'Comp-K': cname=0 results
  MISS  'Comp-L': cname=0 results
  MISS  'Comp-M': cname=0 results
  MISS  '15a': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MISS  '15b': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MATCH 'MZ1' via cname: CID=122201421, InChIKey=PTAMRJLIOCHJMQ-PYNGZGNASA-N
  MATCH 'MZ2' via cname: CID=24768531, InChIKey=ZDEYHQOBNVRHPY-POAKBVNNSA-N
  MATCH 'dBET6' via cname: CID=121427831, InChIKey=JGQPZPLJOBHHBK-UFXYQILXSA-N
  MATCH 'dBET23' via cname: CID=124190790, InChIKey=ZIHIUFZFPMILIG-XLTVJXRZSA-N
  MATCH 'dBET70' via cname: CID=132427802, InChIKey=VDRKZYYQEGSLIS-XLTVJXRZSA-N
  MATCH 'dBET1' via cname: CID=91799313, InChIKey=LKEGXJXRNBALBV-PMCHYTPCSA-N
  MATCH 'dBET57' via cname: CID=118912822, InChIKey=CZRLOIDJCMKJHE-UXMRNZNESA-N
  MATCH 'ZXH-3-26' via cname: CID=132427808, InChIKey=OTKOFICOCDRNDA-PMCHYTPCSA-N
  MATCH 'C004019' via cname: CID=164889480, InChIKey=IXTMPMLKABNFTQ-LLIFGLRNSA-N
  MATCH 'NR-V04' via cname: CID=166998154, InChIKey=GAZVCLAVEAXIQM-ZVXNWPGJSA-N
  MATCH 'MZ1' via cname: CID=122201421, InChIKey=PTAMRJLIOCHJMQ-PYNGZGNASA-N
  MATCH 'ARV-771' via cname: CID=126619980, InChIKey=PQOGZKGXGLHDGS-QQRWPDCKSA-N
  MISS  'OMZ1': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MATCH 'QC-01-175' via cname: CID=139593563, InChIKey=NWTCZTAQSRLSCP-UHFFFAOYSA-N
  MISS  'FMF-06-038': cname=0 results
  MISS  'FMF-06-049': cname=0 results
  MATCH 'CP5V' via cname: CID=139600343, InChIKey=BQQILUVLGKHSNJ-NWRQRLFSSA-N
  MATCH 'DT2216' via cname: CID=139331475, InChIKey=PXVFFBGSTYQHRO-REQIQPEASA-N
  MATCH 'PROTAC 3' via cname: CID=135156947, InChIKey=NICKHWYZMNLEPJ-TZSMONEZSA-N
  MATCH 'TP1L' via cname: CID=169494290, InChIKey=TYEKCBCNQAFGHN-QSITVTTKSA-N
  MISS  'TPiL': cname=0 results
  MISS  'TC5L': cname=0 results
  MISS  'TC6L': cname=0 results
  MISS  'TC4L': cname=0 results
  MISS  'TC7L': cname=0 results
  MISS  'TP8L': cname=0 results
  MISS  'TC5P': cname=0 results
  MISS  'TC6P': cname=0 results
  MISS  'TC4P': cname=0 results
  MISS  'TC7P': cname=0 results
  MISS  'TC8P': cname=0 results
  MISS  'TC9P': cname=0 results
  MISS  'DU14b': cname=0 results
  MATCH 'DD-03-171' via cname: CID=138059681, InChIKey=QBPVFCNYKUENHU-UHFFFAOYSA-N
  MATCH 'Pomalidomide' via cname: CID=134780, InChIKey=UVSMNLNDYGZFPF-UHFFFAOYSA-N
  MATCH 'CC220' via cname: CID=67335295, InChIKey=IXZOHGPZAQLIBH-NRFANRHFSA-N
  MISS  'PS-6': skip: no usable name and no IUPAC/SMILES
  MATCH 'SJF-0628' via cname: CID=146547699, InChIKey=MBCAVOCJJAQHHT-FGUOTCRGSA-N
  MATCH 'RC32' via cname: CID=156599864, InChIKey=XCSUEITWRRFFMN-LPIXFUNRSA-N
  MISS  'NP8': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MATCH 'd9A-2' via cname: CID=156726730, InChIKey=WMBSSRAFHKGIRA-UHFFFAOYSA-N
  MISS  'dTAG13': cname=0 results
  MISS  'dTAG7': cname=0 results
  MATCH 'MD13' via cname: CID=163342432, InChIKey=HAHDZDUOFHMMEA-UHFFFAOYSA-N
  MISS  'MD9': skip: no usable name and no IUPAC/SMILES
  MISS  'CRBN_1b': cname=0 results
  MISS  'CRBN_1e': cname=0 results
  MATCH 'JMC-137' via cname: CID=168275983, InChIKey=HWEFEZUTECUWNS-IIWOMYBWSA-N
  MATCH 'macroPROTAC-1' via cname: CID=145704688, InChIKey=GMEHQGWGMMKWAX-NIQMDXQVSA-N
  MATCH 'NC-1' via cname: CID=168316255, InChIKey=QSLUWEWRUWTRBT-QQKHLPPFSA-N
  MATCH 'IR-1' via cname: CID=168316234, InChIKey=AWOLTJZICWTLFS-AHDGVXFFSA-N
  MISS  'RC-2': cname=0 results
  MATCH 'QC-01–175' via cname: CID=139593563, InChIKey=NWTCZTAQSRLSCP-UHFFFAOYSA-N
  MISS  'P9': skip: no usable name and no IUPAC/SMILES
  MISS  'SC5': skip: no usable name and no IUPAC/SMILES
  MISS  'SC7': skip: no usable name and no IUPAC/SMILES
  MISS  'SC9': cname=0 results
  MISS  'SC11': cname=0 results
  MISS  'P3': skip: no usable name and no IUPAC/SMILES
  MISS  'P4': skip: no usable name and no IUPAC/SMILES
  MISS  'P5': skip: no usable name and no IUPAC/SMILES
  MISS  'SC10': skip: no usable name and no IUPAC/SMILES
  MISS  'P7': skip: no usable name and no IUPAC/SMILES
  MISS  'P8': skip: no usable name and no IUPAC/SMILES
  MISS  'P10': cname=0 results
  MISS  'RGC-01-05-18': cname=0 results
  MISS  '8a': skip: no usable name and no IUPAC/SMILES
  MATCH 'VZ185' via cname: CID=138454768, InChIKey=ZAGCLFXBHOXXEN-JPTLTNPLSA-N
  MATCH 'dBRD9' via cname: CID=135397681, InChIKey=AIOCFZJGGGEWDK-UHFFFAOYSA-N
  MISS  'DBt-5': cname=0 results
  MISS  'DBt-10': skip: no usable name and no IUPAC/SMILES
  MISS  'CDa-1': cname=0 results
  MISS  'DDa-1': cname=0 results
  MATCH 'DT2216' via cname: CID=139331475, InChIKey=PXVFFBGSTYQHRO-REQIQPEASA-N
  MISS  'D3': skip: no usable name and no IUPAC/SMILES
  MISS  'D10': skip: no usable name and no IUPAC/SMILES
  MISS  'D12': skip: no usable name and no IUPAC/SMILES
  MISS  'D14': cname=0 results
  MISS  'D15': skip: no usable name and no IUPAC/SMILES
  MATCH 'dBET57' via cname: CID=118912822, InChIKey=CZRLOIDJCMKJHE-UXMRNZNESA-N
  MATCH 'A6' via SMILES: CID=166642468, InChIKey=FQLCLMHMOFLVSV-UHFFFAOYSA-N
  MISS  'XR-4': cname=0 results
  MISS  '2': skip: no usable name and no IUPAC/SMILES
  MISS  'KTX-335': cname=0 results
  MISS  'KTX-652': cname=0 results
  MISS  'KTX-978': cname=0 results
  MISS  'CRBN(BRAF)-24': cname=0 results
  MISS  'Cpd 1': skip: no usable name and no IUPAC/SMILES
  MISS  'B1-10J': cname=0 results
  MISS  'B1-10P': cname=0 results
  MISS  'B2-12P': cname=0 results
  MISS  'B1-10': cname=0 results
  MISS  'B2-12': cname=0 results
  MISS  'B2-14': cname=0 results
  MATCH 'A947' via cname: CID=139546336, InChIKey=QQVCUSPUMMUFTD-NCXNEFEISA-N
  MISS  'BTR2004': cname=0 results
  MISS  'FS-ARV-825': cname=0 results
  MATCH 'ARV-825' via cname: CID=92044400, InChIKey=RWLOGRLTDKDANT-TYIYNAFKSA-N

--- PubChem Results ---
Matched triples: 59/163
Standard_InChIKey filled: 171
IUPAC_Name filled: 87
SMILES filled: 150
Standard_InChIKey still missing: 158

In [10]:
output_path = os.path.join(data_dir, "260502_merged_protac_data_processed_cleaned_inchikey_pubchem_1st.csv")
merged_cleaned_protac.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_protac.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_1st/260502_merged_protac_data_processed_cleaned_inchikey_pubchem_1st.csv
Shape: (714, 18)

### Add connectivity_key

In [11]:
merged_cleaned_protac = add_connectivity_key(merged_cleaned_protac)

In [12]:
merged_cleaned_protac

,DOI,Compound_Name,IUPAC_Name,SMILES,SMILES_Source,Degradation_Target,Recruiter,Assay,Cell_Line,DC50,DC50_units,DC50_h,Dmax,Dmax_h,Dmax_conc,Standard_InChIKey,Standard_InChIKey_Source,IUPAC_Name_Source,Connectivity_Key
0,10.1038/s42003-020-0868-6,4,(S)-N-((S)-1-(1-(2-(4-(2-((6-(tert-Butylsulfon...,C(C)(C)(C)S(=O)(=O)C=1C=C2C(=NC=NC2=CC1OCCN1CC...,OPSIN,RIPK2,IAP,Simple Western immunoassay (capillary-based),human PBMCs,12.6,nM,24,69.2±11.5,24,NaN,HZMQXNZSFFXKMT-LCPJFFRWSA-N,OPSIN,<NA>,HZMQXNZSFFXKMT
1,10.1038/s42003-020-0868-6,6,"5-(4-(3-((6-(tert-Butylsulfonyl)-4-((4,5-dimet...",C(C)(C)(C)S(=O)(=O)C=1C=C2C(=NC=NC2=CC1OCCCN1C...,OPSIN,RIPK2,IAP,Simple Western immunoassay (capillary-based),human PBMCs,0.4,nM,24,94.3±3.2,24,NaN,CHNBEZLJAQUZEX-LFRONEFISA-N,OPSIN,<NA>,CHNBEZLJAQUZEX
2,10.1038/s42003-020-0868-6,2,(S)-7-(2-(2-(2-(2-((4-(benzo[d]thiazol-5-ylami...,NaN,<NA>,RIPK2,IAP,Capillary-based immunoassay (Simple Western),THP-1,0.4,nM,18,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>
3,10.1038/s42003-020-0868-6,1,NaN,NaN,<NA>,RIPK2,VHL,Capillary-based immunoassay (Simple Western),THP-1,2.0,nM,18,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>
4,10.1038/s42003-020-0868-6,3,(S)-14-((4-(Benzo[d]thiazol-5-ylamino)-6-(tert...,S1C=NC2=C1C=CC(=C2)NC2=CC=NC1=CC(=C(C=C21)S(=O...,OPSIN,RIPK2,cereblon,Capillary-based immunoassay (Simple Western),THP-1,2.5,nM,18,NaN,NaN,NaN,BRZGXSNAXRPPFI-DHUJRADRSA-N,OPSIN,<NA>,BRZGXSNAXRPPFI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,10.1101/gad.349717.122,BTR2004,NaN,NaN,<NA>,BRD3,KLHL20,Western blot,PC3,~87,nM,4 h,100,4 h,10 μM,<NA>,<NA>,<NA>,<NA>
710,10.1101/gad.349717.122,BTR2004,NaN,NaN,<NA>,BRD4,KLHL20,Western blot,PC3,~777,nM,4 h,100,4 h,10 μM,<NA>,<NA>,<NA>,<NA>
711,10.1039/d3cb00103b,FS-ARV-825,NaN,NaN,<NA>,GSPT1,CRBN,Imaging-based GFP/mCherry ratio (high-content ...,Flp293T GFP-GSPT1(389-499)/mCherry,∼500,nM,5,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>
712,10.1039/d3cb00103b,ARV-825,"2-[(9S)-7-(4-chlorophenyl)-4,5,13-trimethyl-3-...",CC1=C(SC2=C1C(=N[C@H](C3=NN=C(N32)C)CC(=O)NC4=...,PUBCHEM,IKZF1,CRBN,HiBiT lytic luminescence assay,MOLT4 HiBiT-IKZF1,26 ± 2,nM,24,~95,24,NaN,RWLOGRLTDKDANT-TYIYNAFKSA-N,PUBCHEM,PUBCHEM,RWLOGRLTDKDANT
713,10.1039/d3cb00103b,FS-ARV-825,NaN,NaN,<NA>,IKZF1,CRBN,HiBiT lytic luminescence assay,MOLT4 HiBiT-IKZF1,200 ± 28,nM,24,~95,24,NaN,<NA>,<NA>,<NA>,<NA>

In [13]:
output_path = os.path.join(data_dir, "260502_merged_protac_data_processed_cleaned_inchikey_pubchem_ck_1st.csv")
merged_cleaned_protac.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_protac.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_1st/260502_merged_protac_data_processed_cleaned_inchikey_pubchem_ck_1st.csv
Shape: (714, 19)

# Molecular Glues

### Remove rows where DC50 & Dmax are both empty

In [15]:
merged_cleaned_glues = remove_empty_dc50_dmax(merged_glues)

Removed 91 rows where both DC50 and Dmax are empty
Shape: 337 -> 246

In [16]:
data_dir_glues = "/Users/yaochenr/project/molecular_glue_extractor/output/results/260430_glue_data"
os.makedirs(data_dir_glues, exist_ok=True)
output_merged = os.path.join(data_dir_glues, "260430_merged_glue_data_processed_cleaned.csv")
merged_cleaned_glues.to_csv(output_merged, index=False)
print(f"Saved cleaned merged data to: {output_merged}")
print(f"Shape: {merged_cleaned_glues.shape}")

Saved cleaned merged data to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260430_glue_data/260430_merged_glue_data_processed_cleaned.csv
Shape: (246, 14)

### Add Standard InChIKey via OPSIN

In [17]:
merged_cleaned_glues = add_inchikey_opsin(merged_cleaned_glues)

Rows with SMILES from paper: 8
Processed 50/246 rows...
Processed 100/246 rows...

Done! Success: 138, Failed: 1, Skipped (no IUPAC): 107
Standard_InChIKey filled: 138
SMILES from PAPER: 8
SMILES from OPSIN: 132
SMILES still missing: 106

--- Failed rows ---
{'row': 3, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS64', 'IUPAC_Name': '(R)-2-((6-((4,5-difluoro-1H-benzo[d]imidazol-2-yl)methyl)amino)-9-isopropyl-9H-purin-2 yl)amino)buta'}

In [18]:
output_path = os.path.join(data_dir_glues, "260430_merged_glue_data_processed_cleaned_inchikey.csv")
merged_cleaned_glues.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_glues.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260430_glue_data/260430_merged_glue_data_processed_cleaned_inchikey.csv
Shape: (246, 17)

### PubChem Search

In [19]:
merged_cleaned_glues = pubchem_search(merged_cleaned_glues)

Rows missing Standard_InChIKey: 108 (55 unique (cname, iupac, smiles) triples)
  MATCH 'DS64' via cname: CID=168499496, InChIKey=DCTODZNTFHJKGP-LLVKDONJSA-N
  MATCH 'dBET57' via cname: CID=118912822, InChIKey=CZRLOIDJCMKJHE-UXMRNZNESA-N
  MATCH 'A6' via SMILES: CID=166642468, InChIKey=FQLCLMHMOFLVSV-UHFFFAOYSA-N
  MATCH 'DS02' via cname: CID=168499469, InChIKey=KLBKESYFUKKKSS-LJQANCHMSA-N
  MATCH 'DS66' via cname: CID=168499478, InChIKey=CWXUALXYQXQCPS-LJQANCHMSA-N
  MISS  'iDeg-6': cname=0 results
  MATCH 'DS47' via cname: CID=168499490, InChIKey=LVVKHGPMCAECNF-CONSDPRKSA-N
  MISS  'Z10': cname=0 results
  MISS  'DS_CR8': cname=0 results
  MATCH 'THAL-SNS032' via cname: CID=131801483, InChIKey=BXDZOYLPNAIDOC-UHFFFAOYSA-N
  MISS  'Z12': cname=0 results
  MATCH 'BSJ-4-116' via cname: CID=155235839, InChIKey=YJOJMGTVKMABKQ-FIQOPJFZSA-N
  MISS  '21195': skip: no usable name and no IUPAC/SMILES
  MATCH 'SR-4835' via cname: CID=139600338, InChIKey=FSELUFUYNUNZKD-UHFFFAOYSA-N
  MISS  '919278': skip: no usable name and no IUPAC/SMILES
  MATCH 'dCeMM2' via cname: CID=5286209, InChIKey=VFWVTIHYVUKNGR-UHFFFAOYSA-N
  MATCH 'dCeMM4' via cname: CID=53546112, InChIKey=BPWZJVKIVHVVHP-UHFFFAOYSA-N
  MATCH 'HQ461' via cname: CID=49677967, InChIKey=QMRBCNQCRMTXBE-UHFFFAOYSA-N
  MISS  'Z11': cname=0 results
  MISS  'CR8': cname=0 results
  MISS  'VNPP433-3β': cname=0 results
  MATCH 'lenalidomide' via cname: CID=216326, InChIKey=GOTYRUGSSMKFNF-UHFFFAOYSA-N
  MISS  '5': skip: no usable name and no IUPAC/SMILES
  MISS  '13': skip: no usable name and no IUPAC/SMILES
  MATCH 'SJ3149' via cname: CID=168511381, InChIKey=AJUZTJBGJWQZFW-UHFFFAOYSA-N
  MISS  'CU-0906': cname=0 results
  MISS  'MG-Lin1': cname=0 results
  MATCH 'pomalidomide' via cname: CID=134780, InChIKey=UVSMNLNDYGZFPF-UHFFFAOYSA-N
  MISS  'GNE011': cname=0 results
  MATCH 'MMH1' via cname: CID=169450066, InChIKey=AEEGEVCKDJFBRN-IBGZPJMESA-N
  MISS  'MMH249': cname=0 results
  MISS  'MMH287': cname=0 results
  MATCH 'MMH2' via cname: CID=169450067, InChIKey=FZRRESXAODIMQN-IBGZPJMESA-N
  MATCH 'TMX1' via cname: CID=168264924, InChIKey=SJISOGWQGIVAGX-DUIUGDAFSA-N
  MISS  'TMX4128': cname=0 results
  MISS  'TMX458': cname=0 results
  MATCH 'CC-90009' via cname: CID=118647211, InChIKey=PWBHUSLMHZLGRN-UHFFFAOYSA-N
  MISS  '13-7': skip: no usable name and no IUPAC/SMILES
  MISS  '10': skip: no usable name and no IUPAC/SMILES
  MISS  '11': skip: no usable name and no IUPAC/SMILES
  MISS  '12': skip: no usable name and no IUPAC/SMILES
  MISS  '14': skip: no usable name and no IUPAC/SMILES
  MISS  '15': skip: no usable name and no IUPAC/SMILES
  MISS  '16b': cname=0 results
  MISS  '16': skip: no usable name and no IUPAC/SMILES
  MISS  '7': skip: no usable name and no IUPAC/SMILES
  MISS  '8': skip: no usable name and no IUPAC/SMILES
  MISS  '9': skip: no usable name and no IUPAC/SMILES
  MATCH 'DKY709' via cname: CID=137519326, InChIKey=OMISHRJQMYQPMG-UHFFFAOYSA-N
  MATCH 'PVTX-405' via cname: CID=169201312, InChIKey=SITNTOVOBBQZJQ-VWLOTQADSA-N
  MATCH 'PT-179' via cname: CID=163294079, InChIKey=CCCSRHUSXCBFJZ-UHFFFAOYSA-N
  MISS  'MGD-15': cname=0 results
  MISS  'MGD-18': cname=0 results
  MATCH 'MGD-28' via cname: CID=172871692, InChIKey=JICHBFQDRLGJTM-UHFFFAOYSA-N
  MISS  'MGD-4': cname=0 results

--- PubChem Results ---
Matched triples: 23/55
Standard_InChIKey filled: 58
IUPAC_Name filled: 57
SMILES filled: 56
Standard_InChIKey still missing: 50

In [20]:
output_path = os.path.join(data_dir_glues, "260430_merged_glue_data_processed_cleaned_inchikey_pubchem.csv")
merged_cleaned_glues.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_glues.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260430_glue_data/260430_merged_glue_data_processed_cleaned_inchikey_pubchem.csv
Shape: (246, 18)

### Add connectivity_key

In [21]:
merged_cleaned_glues = add_connectivity_key(merged_cleaned_glues)

In [22]:
merged_cleaned_glues[['Compound_Name', 'Standard_InChIKey', 'Connectivity_Key']]

    Compound_Name            Standard_InChIKey Connectivity_Key
0             43h  NTNMFROSEFWETI-XIJSCUBXSA-N   NTNMFROSEFWETI
1             44h  BIVJJLVZJPBUMK-XIJSCUBXSA-N   BIVJJLVZJPBUMK
2              51  YACBBDOEMCACOF-UHFFFAOYSA-N   YACBBDOEMCACOF
3            DS64  DCTODZNTFHJKGP-LLVKDONJSA-N   DCTODZNTFHJKGP
4            DS18  DPCUNIIUTMKIKJ-UHFFFAOYSA-N   DPCUNIIUTMKIKJ
..            ...                          ...              ...
241  lenalidomide  GOTYRUGSSMKFNF-UHFFFAOYSA-N   GOTYRUGSSMKFNF
242  pomalidomide  UVSMNLNDYGZFPF-UHFFFAOYSA-N   UVSMNLNDYGZFPF
243  pomalidomide  UVSMNLNDYGZFPF-UHFFFAOYSA-N   UVSMNLNDYGZFPF
244  pomalidomide  UVSMNLNDYGZFPF-UHFFFAOYSA-N   UVSMNLNDYGZFPF
245  pomalidomide  UVSMNLNDYGZFPF-UHFFFAOYSA-N   UVSMNLNDYGZFPF

[246 rows x 3 columns]

In [23]:
output_path = os.path.join(data_dir_glues, "260430_merged_glue_data_processed_cleaned_inchikey_pubchem_ck.csv")
merged_cleaned_glues.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_glues.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260430_glue_data/260430_merged_glue_data_processed_cleaned_inchikey_pubchem_ck.csv
Shape: (246, 19)