**Molecular glue and PROTACs LLM prediction vs. ground truth for the 2nd run**

# Processing Functions

In [ ]:
import requests
import time
from urllib.parse import quote
import pubchempy as pcp


OPSIN_BASE = "https://www.ebi.ac.uk/opsin/ws"
_DASH_CHARS = "‐‑‒–—―−﹣－"
_DASH_TRANS = str.maketrans({c: "-" for c in _DASH_CHARS})


def _normalize_dashes(s):
    if not isinstance(s, str):
        return s
    return s.translate(_DASH_TRANS)


PUBCHEM_BLOCKLIST = {
    "Mei", "Po", "Le",
    "LC-4", "LC-6",
    "D10", "D12", "D15",
    "A13", "13b",
    "SC5", "SC7", "SC10",
    "DBt-10",
    "PS-6",
    "MD9",
    "Cpd 1",
}


def remove_empty_dc50_dmax(df):
    before = len(df)
    cleaned = df.dropna(subset=["DC50", "Dmax"], how="all")
    cleaned = cleaned[~(
        cleaned["DC50"].astype(str).str.strip().isin(["", "nan"])
        & cleaned["Dmax"].astype(str).str.strip().isin(["", "nan"])
    )]
    cleaned = cleaned.reset_index(drop=True)
    after = len(cleaned)
    print(f"Removed {before - after} rows where both DC50 and Dmax are empty")
    print(f"Shape: {before} -> {after}")
    return cleaned


def add_inchikey_opsin(df, sleep_sec=0.1):
    df = df.copy()
    df["Standard_InChIKey"] = pd.NA
    df["Standard_InChIKey_Source"] = pd.NA
    if "SMILES_Source" not in df.columns:
        df["SMILES_Source"] = pd.NA

    has_smiles = df["SMILES"].notna() & (df["SMILES"].astype(str).str.strip() != "")
    df.loc[has_smiles, "SMILES_Source"] = "PAPER"
    print(f"Rows with SMILES from paper: {has_smiles.sum()}")

    success, fail, skip = 0, 0, 0
    failed_rows = []

    for idx, row in df.iterrows():
        iupac = row["IUPAC_Name"]
        if pd.isna(iupac) or str(iupac).strip() == "":
            skip += 1
            continue

        url = f"{OPSIN_BASE}/{quote(str(iupac).strip(), safe='')}.json"
        try:
            resp = requests.get(url, timeout=30)
            if resp.status_code == 200:
                data = resp.json()
                inchikey = data.get("stdinchikey")
                smiles = data.get("smiles")
                if inchikey:
                    df.at[idx, "Standard_InChIKey"] = inchikey
                    df.at[idx, "Standard_InChIKey_Source"] = "OPSIN"
                if not has_smiles[idx] and smiles:
                    df.at[idx, "SMILES"] = smiles
                    df.at[idx, "SMILES_Source"] = "OPSIN"
                success += 1
            else:
                failed_rows.append({"row": idx, "status": resp.status_code, "DOI": row["DOI"], "Compound_Name": row["Compound_Name"], "IUPAC_Name": str(iupac)[:100]})
                fail += 1
        except Exception as e:
            failed_rows.append({"row": idx, "error": str(e), "DOI": row["DOI"], "Compound_Name": row["Compound_Name"], "IUPAC_Name": str(iupac)[:100]})
            fail += 1

        if (idx + 1) % 50 == 0:
            print(f"Processed {idx + 1}/{len(df)} rows...")
        time.sleep(sleep_sec)

    cols = list(df.columns)
    smiles_idx = cols.index("SMILES")
    cols.remove("SMILES_Source")
    cols.insert(smiles_idx + 1, "SMILES_Source")
    df = df[cols]

    print(f"\nDone! Success: {success}, Failed: {fail}, Skipped (no IUPAC): {skip}")
    print(f"Standard_InChIKey filled: {df['Standard_InChIKey'].notna().sum()}")
    print(f"SMILES from PAPER: {(df['SMILES_Source'] == 'PAPER').sum()}")
    print(f"SMILES from OPSIN: {(df['SMILES_Source'] == 'OPSIN').sum()}")
    print(f"SMILES still missing: {df['SMILES'].isna().sum()}")
    if failed_rows:
        print(f"\n--- Failed rows ---")
        for fr in failed_rows:
            print(fr)
    return df


def pubchem_search(df, sleep_sec=0.3, blocklist=None, min_name_length=3):
    """Fill Standard_InChIKey (and IUPAC_Name / SMILES if missing) via PubChem.
    """
    df = df.copy()
    if blocklist is None:
        blocklist = PUBCHEM_BLOCKLIST

    def has_value(v):
        return pd.notna(v) and str(v).strip() != "" and str(v).strip().lower() != "nan"

    def is_numeric_name(s):
        return s.replace(".", "").replace("-", "").isdigit()

    def cname_usable(c):
        if not c:
            return False
        if c in blocklist or _normalize_dashes(c) in blocklist:
            return False
        if is_numeric_name(c):
            return False
        if len(c) < min_name_length:
            return False
        return True

    def search_name_with_synonym(raw_query):
        query = _normalize_dashes(raw_query).strip()
        if not query:
            return None, "empty after normalization"
        try:
            compounds = pcp.get_compounds(query, "name")
            if not compounds:
                return None, "0 results"
            top = compounds[0]
            syn_url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/{top.cid}/synonyms/JSON"
            syn_resp = requests.get(syn_url, timeout=30)
            if syn_resp.status_code != 200:
                return None, f"synonyms HTTP {syn_resp.status_code} (CID={top.cid})"
            syns = syn_resp.json()["InformationList"]["Information"][0]["Synonym"]
            q_cmp = query.lower()
            if not any(_normalize_dashes(s).lower() == q_cmp for s in syns):
                return None, f"not in synonyms (CID={top.cid})"
            return {"cid": top.cid, "iupac_name": top.iupac_name,
                    "smiles": top.smiles, "inchikey": top.inchikey}, "ok"
        except Exception as e:
            return None, f"error: {e}"

    def search_smiles(query):
        try:
            compounds = pcp.get_compounds(query, "smiles")
            if not compounds:
                return None, "0 results"
            top = compounds[0]
            return {"cid": top.cid, "iupac_name": top.iupac_name,
                    "smiles": top.smiles, "inchikey": top.inchikey}, "ok"
        except Exception as e:
            return None, f"error: {e}"

    def chem_search(iupac, smiles):
        if iupac:
            r, reason = search_name_with_synonym(iupac)
            time.sleep(sleep_sec)
            if r:
                return r, "IUPAC", reason
            iupac_reason = reason
        else:
            iupac_reason = "no IUPAC"
        if smiles:
            r, reason = search_smiles(smiles)
            time.sleep(sleep_sec)
            if r:
                return r, "SMILES", reason
            smiles_reason = reason
        else:
            smiles_reason = "no SMILES"
        return None, None, f"IUPAC={iupac_reason}, SMILES={smiles_reason}"

    for col in ("IUPAC_Name_Source", "Standard_InChIKey",
                "Standard_InChIKey_Source", "SMILES_Source"):
        if col not in df.columns:
            df[col] = pd.NA

    needs_key = df["Standard_InChIKey"].isna() | (df["Standard_InChIKey"].astype(str).str.strip() == "")
    to_search = df[needs_key].index

    queries = {}
    for idx in to_search:
        cname = str(df.at[idx, "Compound_Name"]).strip() if has_value(df.at[idx, "Compound_Name"]) else ""
        iupac = str(df.at[idx, "IUPAC_Name"]).strip()    if has_value(df.at[idx, "IUPAC_Name"])    else ""
        smi   = str(df.at[idx, "SMILES"]).strip()        if has_value(df.at[idx, "SMILES"])        else ""
        queries.setdefault((cname, iupac, smi), []).append(idx)

    print(f"Rows missing Standard_InChIKey: {len(to_search)} ({len(queries)} unique (cname, iupac, smiles) triples)")

    def short(s, n=40):
        return (s[:n] + "...") if s and len(s) > n else s

    cache = {}
    for (cname, iupac, smi), idxs in queries.items():
        usable_c = cname_usable(cname)
        has_chem = bool(iupac) or bool(smi)
        cs = short(cname) if cname else "(no cname)"

        result, method, reason = None, None, ""

        if usable_c and not has_chem:
            r, reason_c = search_name_with_synonym(cname)
            time.sleep(sleep_sec)
            if r:
                result, method, reason = r, "cname", reason_c
            else:
                reason = f"cname={reason_c}"
        elif usable_c and has_chem:
            r, reason_c = search_name_with_synonym(cname)
            time.sleep(sleep_sec)
            if r:
                result, method, reason = r, "cname", reason_c
            else:
                result, method, reason_chem = chem_search(iupac, smi)
                reason = f"cname={reason_c}; {reason_chem}" if not result else f"after cname miss: {reason_chem}"
        elif not usable_c and has_chem:
            result, method, reason_chem = chem_search(iupac, smi)
            reason = f"cname unusable; {reason_chem}"
        else:
            reason = "skip: no usable name and no IUPAC/SMILES"

        cache[(cname, iupac, smi)] = result

        if result:
            print(f"  MATCH '{cs}' via {method}: CID={result['cid']}, InChIKey={result['inchikey']}")
        else:
            print(f"  MISS  '{cs}': {reason}")

    filled_key = filled_iupac = filled_smi = 0
    for (cname, iupac, smi), idxs in queries.items():
        result = cache[(cname, iupac, smi)]
        if result is None:
            continue
        for idx in idxs:
            if result["inchikey"]:
                df.at[idx, "Standard_InChIKey"] = result["inchikey"]
                df.at[idx, "Standard_InChIKey_Source"] = "PUBCHEM"
                filled_key += 1
            if not has_value(df.at[idx, "IUPAC_Name"]) and result.get("iupac_name"):
                df.at[idx, "IUPAC_Name"] = result["iupac_name"]
                df.at[idx, "IUPAC_Name_Source"] = "PUBCHEM"
                filled_iupac += 1
            if not has_value(df.at[idx, "SMILES"]) and result.get("smiles"):
                df.at[idx, "SMILES"] = result["smiles"]
                df.at[idx, "SMILES_Source"] = "PUBCHEM"
                filled_smi += 1

    matched = sum(1 for v in cache.values() if v is not None)
    print(f"\n--- PubChem Results ---")
    print(f"Matched triples: {matched}/{len(queries)}")
    print(f"Standard_InChIKey filled: {filled_key}")
    print(f"IUPAC_Name filled: {filled_iupac}")
    print(f"SMILES filled: {filled_smi}")
    print(f"Standard_InChIKey still missing: {(df['Standard_InChIKey'].isna() | (df['Standard_InChIKey'].astype(str).str.strip() == '')).sum()}")
    return df

def add_connectivity_key(df):
    if 'Standard_InChIKey' in df.columns:
        df['Connectivity_Key'] = df['Standard_InChIKey'].str[:14]
    return df

# Porcess PROTACs Extracted Data

In [1]:
import pandas as pd
import os
import glob


base_dir = "/Users/yaochenr/project/molecular_glue_extractor/output/results"
batches = {
    "batch_1": "260501_1226",
    "batch_2": "260501_2158",
    "batch_3": "260501_2234",
    "batch_4": "260501_2302",
    "batch_5": "260501_2332",
    "batch_6": "260501_2358",
    "batch_7": "260502_0031",
    "batch_8": "260502_0057",
    "batch_9": "260502_0117",
    "batch_10": "260502_0142",
    "batch_11": "260502_0203",
    "batch_12": "260502_0227",
    "batch_13": "260502_0253",
    "batch_14": "260502_0312",
}

dfs = []

for batch_name, folder in batches.items():
    path = os.path.join(base_dir, folder, "data_processed.csv")
    df_protacs = pd.read_csv(path)
    dfs.append(df_protacs)
    print(f"{batch_name} ({folder}): {len(df_protacs)} rows")

merged_protacs = pd.concat(dfs, ignore_index=True)
if "source" in merged_protacs.columns:
    merged_protacs = merged_protacs.drop(columns=["source"])
print(f"\nTotal rows: {len(merged_protacs)}")
print(f"Unique DOIs: {merged_protacs['DOI'].nunique()}")
print(f"Unknown DOIs: {(merged_protacs['DOI'] == 'Unknown').sum()}")
print(f"Columns: {list(merged_protacs.columns)}")
merged_protacs.head()

batch_1 (260501_1226): 38 rows
batch_2 (260501_2158): 45 rows
batch_3 (260501_2234): 35 rows
batch_4 (260501_2302): 142 rows
batch_5 (260501_2332): 110 rows
batch_6 (260501_2358): 48 rows
batch_7 (260502_0031): 46 rows
batch_8 (260502_0057): 21 rows
batch_9 (260502_0117): 65 rows
batch_10 (260502_0142): 49 rows
batch_11 (260502_0203): 38 rows
batch_12 (260502_0227): 33 rows
batch_13 (260502_0253): 45 rows
batch_14 (260502_0312): 70 rows

Total rows: 785
Unique DOIs: 118
Unknown DOIs: 0
Columns: ['DOI', 'Compound_Name', 'IUPAC_Name', 'SMILES', 'Degradation_Target', 'Recruiter', 'Assay', 'Cell_Line', 'DC50', 'DC50_units', 'DC50_h', 'Dmax', 'Dmax_h', 'Dmax_conc']

,DOI,Compound_Name,IUPAC_Name,SMILES,Degradation_Target,Recruiter,Assay,Cell_Line,DC50,DC50_units,DC50_h,Dmax,Dmax_h,Dmax_conc
0,10.1038/s42003-020-0868-6,1,NaN,NaN,RIPK2,VHL,capillary-based immunoassay,THP-1,2.0,nM,18 h,NaN,NaN,NaN
1,10.1038/s42003-020-0868-6,2,(S)-7-(2-(2-(2-(2-((4-(benzo[d]thiazol-5-ylami...,NaN,RIPK2,IAP,capillary-based immunoassay,THP-1,0.40,nM,18 h,NaN,NaN,NaN
2,10.1038/s42003-020-0868-6,3,(S)-14-((4-(Benzo[d]thiazol-5-ylamino)-6-(tert...,NaN,RIPK2,cereblon,capillary-based immunoassay,THP-1,2.5,nM,18 h,NaN,NaN,NaN
3,10.1038/s42003-020-0868-6,4,(S)-N-((S)-1-(1-(2-(4-(2-((6-(tert-Butylsulfon...,NaN,RIPK2,IAP,Simple Western (capillary-based) immunoassay,human PBMCs,12.6,nM,24 h,69.2,24 h,NaN
4,10.1038/s42003-020-0868-6,6,"5-(4-(3-((6-(tert-Butylsulfonyl)-4-((4,5-dimet...",NaN,RIPK2,IAP,Simple Western (capillary-based) immunoassay,human PBMCs,0.40,nM,24 h,94.3,24 h,NaN

In [3]:
data_dir = "/Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_2nd"
os.makedirs(data_dir, exist_ok=True)
output_path = os.path.join(data_dir, "260502_merged_protac_data_processed_2nd.csv")
merged_protacs.to_csv(output_path, index=False)
print(f"Saved merged data to: {output_path}")
print(f"Shape: {merged_protacs.shape}")

Saved merged data to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_2nd/260502_merged_protac_data_processed_2nd.csv
Shape: (785, 14)

### Remove rows where DC50 & Dmax are both empty

In [5]:
merged_cleaned_protac = remove_empty_dc50_dmax(merged_protacs)

Removed 117 rows where both DC50 and Dmax are empty
Shape: 785 -> 668

In [ ]:
output_merged = os.path.join(data_dir, "260502_merged_protac_data_processed_cleaned_2nd.csv")
merged_cleaned_protac.to_csv(output_merged, index=False)
print(f"Saved cleaned merged data to: {output_merged}")
print(f"Shape: {merged_cleaned_protac.shape}")

Saved cleaned merged data to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_2nd/260502_merged_protac_data_processed_cleaned_2nd.csv
Shape: (668, 14)

### Add Standard InChIKey via OPSIN

In [7]:
merged_cleaned_protac = add_inchikey_opsin(merged_cleaned_protac)

Rows with SMILES from paper: 102
Processed 50/668 rows...
Processed 100/668 rows...
Processed 150/668 rows...
Processed 250/668 rows...
Processed 300/668 rows...
Processed 350/668 rows...
Processed 400/668 rows...
Processed 450/668 rows...
Processed 500/668 rows...
Processed 550/668 rows...
Processed 650/668 rows...

Done! Success: 383, Failed: 96, Skipped (no IUPAC): 189
Standard_InChIKey filled: 383
SMILES from PAPER: 102
SMILES from OPSIN: 302
SMILES still missing: 264

--- Failed rows ---
{'row': 1, 'status': 404, 'DOI': '10.1038/s42003-020-0868-6', 'Compound_Name': '2', 'IUPAC_Name': '(S)-7-(2-(2-(2-(2-((4-(benzo[d]thiazol-5-ylamino)-6-(tert-butylsulfonyl)quinolin-7-yl)oxy)ethoxy)eth'}
{'row': 50, 'status': 404, 'DOI': '10.1080/14756366.2022.2062338', 'Compound_Name': '16', 'IUPAC_Name': 'N-(2-(2, 6-dioxopiperidin-3-yl)-1,3-dioxoisoindolin-4-yl)-2-(2-(2-(2-(4-methyl-3-oxo-3, 4-dihydroqui'}
{'row': 88, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00771', 'Compound_Name': 'NU223612', 'IUPAC_Name': '(2R)-N-(4-((1-(3-(2-(2-((2-(2,6-Dioxopiperidin-3-yl)-1,3-dioxoisoindolin-4-Yl)amino)ethoxy)ethoxy)pr'}
{'row': 89, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00771', 'Compound_Name': 'NU223612', 'IUPAC_Name': '(2R)-N-(4-((1-(3-(2-(2-((2-(2,6-Dioxopiperidin-3-yl)-1,3-dioxoisoindolin-4-Yl)amino)ethoxy)ethoxy)pr'}
{'row': 92, 'status': 404, 'DOI': '10.1021/jacs.2c05499', 'Compound_Name': 'XL01126', 'IUPAC_Name': '(2S,4R)-1-((R)-3-((((1R,4R)-4-((4-(4-((5-Chloro-4-(methylamino)pyrimidin-2-yl)amino)-3-methoxybenzoy'}
{'row': 93, 'status': 404, 'DOI': '10.1021/jacs.2c05499', 'Compound_Name': 'XL01126', 'IUPAC_Name': '(2S,4R)-1-((R)-3-((((1R,4R)-4-((4-(4-((5-Chloro-4-(methylamino)pyrimidin-2-yl)amino)-3-methoxybenzoy'}
{'row': 98, 'status': 404, 'DOI': '10.1021/jacs.2c05499', 'Compound_Name': 'XL01126', 'IUPAC_Name': '(2S,4R)-1-((R)-3-((((1R,4R)-4-((4-(4-((5-Chloro-4-(methylamino)pyrimidin-2-yl)amino)-3-methoxybenzoy'}
{'row': 99, 'status': 404, 'DOI': '10.1021/jacs.2c05499', 'Compound_Name': 'XL01126', 'IUPAC_Name': '(2S,4R)-1-((R)-3-((((1R,4R)-4-((4-(4-((5-Chloro-4-(methylamino)pyrimidin-2-yl)amino)-3-methoxybenzoy'}
{'row': 100, 'status': 404, 'DOI': '10.1021/jacs.2c05499', 'Compound_Name': 'XL01126', 'IUPAC_Name': '(2S,4R)-1-((R)-3-((((1R,4R)-4-((4-(4-((5-Chloro-4-(methylamino)pyrimidin-2-yl)amino)-3-methoxybenzoy'}
{'row': 101, 'status': 404, 'DOI': '10.1021/jacs.2c05499', 'Compound_Name': 'XL01126', 'IUPAC_Name': '(2S,4R)-1-((R)-3-((((1R,4R)-4-((4-(4-((5-Chloro-4-(methylamino)pyrimidin-2-yl)amino)-3-methoxybenzoy'}
{'row': 167, 'status': 404, 'DOI': '10.1038/s41467-022-33430-6', 'Compound_Name': '22', 'IUPAC_Name': '(2S,4R)-N-(2-(2-(2-(2-(2-(4-(4-bromo-7-cyclopentyl-5-oxo-5,7-dihydrobenzo[4,5]imidazo[1,2 a]quinazol'}
{'row': 168, 'status': 404, 'DOI': '10.1038/s41467-022-33430-6', 'Compound_Name': '22', 'IUPAC_Name': '(2S,4R)-N-(2-(2-(2-(2-(2-(4-(4-bromo-7-cyclopentyl-5-oxo-5,7-dihydrobenzo[4,5]imidazo[1,2 a]quinazol'}
{'row': 169, 'status': 404, 'DOI': '10.1038/s41467-022-33430-6', 'Compound_Name': '22', 'IUPAC_Name': '(2S,4R)-N-(2-(2-(2-(2-(2-(4-(4-bromo-7-cyclopentyl-5-oxo-5,7-dihydrobenzo[4,5]imidazo[1,2 a]quinazol'}
{'row': 170, 'status': 404, 'DOI': '10.1038/s41467-022-33430-6', 'Compound_Name': '22', 'IUPAC_Name': '(2S,4R)-N-(2-(2-(2-(2-(2-(4-(4-bromo-7-cyclopentyl-5-oxo-5,7-dihydrobenzo[4,5]imidazo[1,2 a]quinazol'}
{'row': 219, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6c', 'IUPAC_Name': '4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)-N-(2-(2,6-dioxopip'}
{'row': 220, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6c', 'IUPAC_Name': '4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)-N-(2-(2,6-dioxopip'}
{'row': 221, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6d', 'IUPAC_Name': '2-(4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)piperazin-1-yl)-'}
{'row': 222, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6d', 'IUPAC_Name': '2-(4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)piperazin-1-yl)-'}
{'row': 223, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6e', 'IUPAC_Name': '3-(4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)piperazin-1-yl)-'}
{'row': 224, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6e', 'IUPAC_Name': '3-(4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)piperazin-1-yl)-'}
{'row': 225, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7b', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((E)-3-(2-(2,6-dioxopiperidin-'}
{'row': 226, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7b', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((E)-3-(2-(2,6-dioxopiperidin-'}
{'row': 227, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7e', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-(2-((2-(2,6-dioxopiperidin-3-y'}
{'row': 228, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7e', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-(2-((2-(2,6-dioxopiperidin-3-y'}
{'row': 229, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7f', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}
{'row': 230, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7f', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}
{'row': 231, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '8a', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}
{'row': 232, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '8a', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}
{'row': 233, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '8b', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}
{'row': 234, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '8b', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}
{'row': 252, 'status': 404, 'DOI': '10.1016/j.apsb.2020.11.022', 'Compound_Name': '11a', 'IUPAC_Name': 'N,N -(((Oxybis(ethane-2,1-diyl))bis(oxy))bis(ethane-2,1-diyl))bis(2-(4-(2-(4-(tert-butyl)-2-ethoxyph'}
{'row': 281, 'status': 404, 'DOI': '10.1021/acs.jmedchem.1c02179', 'Compound_Name': '10', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(2-((4-((2-Aminophenyl)carbamoyl)phenyl)amino)-2-oxoethoxy)ethoxy)acetamido)-3,3'}
{'row': 282, 'status': 404, 'DOI': '10.1021/acs.jmedchem.1c02179', 'Compound_Name': '10', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(2-((4-((2-Aminophenyl)carbamoyl)phenyl)amino)-2-oxoethoxy)ethoxy)acetamido)-3,3'}
{'row': 283, 'status': 404, 'DOI': '10.1021/acs.jmedchem.1c02179', 'Compound_Name': '10', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(2-((4-((2-Aminophenyl)carbamoyl)phenyl)amino)-2-oxoethoxy)ethoxy)acetamido)-3,3'}
{'row': 342, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15a', 'IUPAC_Name': '(2R,3R,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 343, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15a', 'IUPAC_Name': '(2R,3R,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 344, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15a', 'IUPAC_Name': '(2R,3R,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 345, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15b', 'IUPAC_Name': '(2R,3S,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 346, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15b', 'IUPAC_Name': '(2R,3S,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 347, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15b', 'IUPAC_Name': '(2R,3S,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 349, 'status': 404, 'DOI': '10.1021/acschembio.5b00216', 'Compound_Name': 'MZ1', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]tria'}
{'row': 350, 'status': 404, 'DOI': '10.1021/acschembio.5b00216', 'Compound_Name': 'MZ1', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]tria'}
{'row': 351, 'status': 404, 'DOI': '10.1021/acschembio.5b00216', 'Compound_Name': 'MZ1', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]tria'}
{'row': 414, 'status': 404, 'DOI': '10.1021/jacsau.3c00228', 'Compound_Name': '21', 'IUPAC_Name': '(R)-2-((2S,3R)-3-amino-2-hydroxy-4-phenylbutanamido)-N-(2-(2-(2-(2-(4-(((2S,4S,11bR)-9,10-bis((3,5-d'}
{'row': 417, 'status': 404, 'DOI': '10.1038/s41591-019-0668-z', 'Compound_Name': 'DT2216', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(7-(4-((R)-3-((4-(N-(4-(4-((4 -chloro-4,4-dimethyl-3,4,5,6-tetrahydro-[1,1 -bipheny'}
{'row': 483, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 484, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 485, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 486, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 487, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 488, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 489, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 491, 'status': 404, 'DOI': '10.1007/s13238-018-0602-z', 'Compound_Name': 'NP8', 'IUPAC_Name': '4-((1-(4-(1-(2-(2-(2-((2-(2,6-dioxopiperidin-3-yl)-1,3-dioxoisoindolin-4-yl)amino)eth oxy)etoxy)ethy'}
{'row': 568, 'status': 404, 'DOI': '10.1038/s41467-023-44237-4', 'Compound_Name': 'DDa-1', 'IUPAC_Name': '2-((6-(4-((1-(8-(4-(4-((2-aminoethyl)amino)-2-(1-(4-chlorophenyl)cyclohexyl)quinazolin-7-yl)piperazi'}
{'row': 573, 'status': 404, 'DOI': '10.1038/s41467-023-44237-4', 'Compound_Name': 'DDa-1', 'IUPAC_Name': '2-((6-(4-((1-(8-(4-(4-((2-aminoethyl)amino)-2-(1-(4-chlorophenyl)cyclohexyl)quinazolin-7-yl)piperazi'}
{'row': 620, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 621, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 622, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 623, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 624, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 625, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 626, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 627, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 628, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 629, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 630, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 631, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 632, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 633, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 634, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 635, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 636, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 637, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 638, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 639, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 640, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 641, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 642, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 643, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 644, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 645, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 646, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 647, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 648, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 649, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 650, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 651, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 652, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 653, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 654, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 655, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 656, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 657, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}

In [8]:
output_path = os.path.join(data_dir, "260502_merged_protac_data_processed_cleaned_inchikey_2nd.csv")
merged_cleaned_protac.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_protac.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_2nd/260502_merged_protac_data_processed_cleaned_inchikey_2nd.csv
Shape: (668, 17)

### PubChem search

In [9]:
merged_cleaned_protac = pubchem_search(merged_cleaned_protac)

Rows missing Standard_InChIKey: 285 (130 unique (cname, iupac, smiles) triples)
  MISS  '1': skip: no usable name and no IUPAC/SMILES
  MISS  '2': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MATCH 'KY02111' via cname: CID=8582409, InChIKey=LXFKEVQQSKQXPR-UHFFFAOYSA-N
  MATCH 'UBX-382' via cname: CID=166545675, InChIKey=WIAKHDZSMZDZQL-UHFFFAOYSA-N
  MISS  '34 (CST651)': cname=0 results
  MISS  '16': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MISS  '2c': skip: no usable name and no IUPAC/SMILES
  MISS  'PRO-6 E': cname=0 results
  MATCH 'LC-3' via cname: CID=156885419, InChIKey=QSJKPPVXARILLJ-GYUTUTRISA-N
  MISS  'LC-4': skip: no usable name and no IUPAC/SMILES
  MATCH 'LC-5' via cname: CID=159353560, InChIKey=LHQBPRGJSOSPMT-JCKBJUPWSA-N
  MISS  'LC-6': skip: no usable name and no IUPAC/SMILES
  MISS  '5': skip: no usable name and no IUPAC/SMILES
  MATCH 'NU223612' via cname: CID=166176927, InChIKey=PLYOHMQINGIYDN-LVMIGYEDSA-N
  MISS  '14': skip: no usable name and no IUPAC/SMILES
  MATCH 'XL01126' via cname: CID=165412689, InChIKey=HKSBXNVKPFTBIG-WUEKOBJSSA-N
  MISS  'XL01134': cname=0 results
  MISS  'A13': skip: no usable name and no IUPAC/SMILES
  MISS  '22': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MISS  '6': skip: no usable name and no IUPAC/SMILES
  MATCH 'ACBI2' via cname: CID=167738509, InChIKey=JBTHUOYYUUPUOZ-LIHPQFRDSA-N
  MATCH 'iRucaparib-AP5' via cname: CID=138857954, InChIKey=CDKSZVJXSCKNQN-UHFFFAOYSA-N
  MATCH 'iRucaparib-AP6' via cname: CID=138857977, InChIKey=YHMDCINUVWULST-UHFFFAOYSA-N
  MATCH 'iVeliparib-AP6' via cname: CID=138857963, InChIKey=XLGCZZCLPNSQNH-YMURELKOSA-N
  MISS  '7': skip: no usable name and no IUPAC/SMILES
  MISS  '11': skip: no usable name and no IUPAC/SMILES
  MISS  '008': skip: no usable name and no IUPAC/SMILES
  MISS  '039': skip: no usable name and no IUPAC/SMILES
  MISS  '13a': cname=0 results
  MISS  '13b': skip: no usable name and no IUPAC/SMILES
  MISS  '13c': cname=0 results
  MISS  '13d': cname=0 results
  MATCH '6c' via SMILES: CID=168296465, InChIKey=GZGWGZGQYMUIEA-UHFFFAOYSA-N
  MATCH '6d' via SMILES: CID=168280695, InChIKey=RAQFFJNNGHFOJQ-UHFFFAOYSA-N
  MATCH '6e' via SMILES: CID=168291380, InChIKey=TXTOISHPMQZJTH-UHFFFAOYSA-N
  MATCH '7b' via SMILES: CID=168273780, InChIKey=AXXVVAVFAZXQRT-ODCIPOBUSA-N
  MATCH '7e' via SMILES: CID=168279854, InChIKey=BASKATKGOOUNTP-UHFFFAOYSA-N
  MATCH '7f' via IUPAC: CID=164887577, InChIKey=XTFJBIUTOVUAPR-UHFFFAOYSA-N
  MATCH '8a' via SMILES: CID=168290140, InChIKey=IEQQOSUYADIJKS-UHFFFAOYSA-N
  MATCH '8b' via SMILES: CID=168281662, InChIKey=BZWXDODDFPHMGW-UHFFFAOYSA-N
  MISS  '11a': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MATCH 'SIAIS361034' via cname: CID=156298253, InChIKey=FBBJZLPPVPILEL-UHFFFAOYSA-N
  MATCH '10' via SMILES: CID=166635273, InChIKey=LDFNYUSMNVVOAO-FHRXIHKVSA-N
  MISS  'Comp-K': cname=0 results
  MISS  'Comp-L': cname=0 results
  MISS  'Comp-M': cname=0 results
  MISS  '15a': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MISS  '15b': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MATCH 'MZ1' via cname: CID=122201421, InChIKey=PTAMRJLIOCHJMQ-PYNGZGNASA-N
  MATCH 'dBET6' via cname: CID=121427831, InChIKey=JGQPZPLJOBHHBK-UFXYQILXSA-N
  MATCH 'dBET23' via cname: CID=124190790, InChIKey=ZIHIUFZFPMILIG-XLTVJXRZSA-N
  MATCH 'dBET70' via cname: CID=132427802, InChIKey=VDRKZYYQEGSLIS-XLTVJXRZSA-N
  MATCH 'dBET1' via cname: CID=91799313, InChIKey=LKEGXJXRNBALBV-PMCHYTPCSA-N
  MATCH 'dBET57' via cname: CID=118912822, InChIKey=CZRLOIDJCMKJHE-UXMRNZNESA-N
  MATCH 'ZXH-3-26' via cname: CID=132427808, InChIKey=OTKOFICOCDRNDA-PMCHYTPCSA-N
  MATCH 'C004019' via cname: CID=164889480, InChIKey=IXTMPMLKABNFTQ-LLIFGLRNSA-N
  MATCH 'NR-V04' via cname: CID=166998154, InChIKey=GAZVCLAVEAXIQM-ZVXNWPGJSA-N
  MATCH 'MZ1' via cname: CID=122201421, InChIKey=PTAMRJLIOCHJMQ-PYNGZGNASA-N
  MATCH 'ARV-771' via cname: CID=126619980, InChIKey=PQOGZKGXGLHDGS-QQRWPDCKSA-N
  MATCH 'QC-01-175' via cname: CID=139593563, InChIKey=NWTCZTAQSRLSCP-UHFFFAOYSA-N
  MISS  'FMF-06-038': cname=0 results
  MISS  'FMF-06-049': cname=0 results
  MISS  'FMF-05-129-2': cname=0 results
  MISS  'FMF-06-066': cname=0 results
  MISS  '21': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MATCH 'CP5V' via cname: CID=139600343, InChIKey=BQQILUVLGKHSNJ-NWRQRLFSSA-N
  MATCH 'DT2216' via cname: CID=139331475, InChIKey=PXVFFBGSTYQHRO-REQIQPEASA-N
  MISS  '3': skip: no usable name and no IUPAC/SMILES
  MATCH 'TP1L' via cname: CID=169494290, InChIKey=TYEKCBCNQAFGHN-QSITVTTKSA-N
  MISS  'TC5L': cname=0 results
  MISS  'TC6L': cname=0 results
  MISS  'TPiL': cname=0 results
  MISS  'TC4L': cname=0 results
  MISS  'TC7L': cname=0 results
  MISS  'TP8L': cname=0 results
  MISS  'TC5P': cname=0 results
  MISS  'TC6P': cname=0 results
  MISS  'TC4P': cname=0 results
  MISS  'TC7P': cname=0 results
  MISS  'TC8P': cname=0 results
  MISS  'TC9P': cname=0 results
  MATCH 'DU14' via cname: CID=129631630, InChIKey=UROAJULLGDEBSL-UHFFFAOYSA-N
  MATCH 'DD-03-171' via cname: CID=138059681, InChIKey=QBPVFCNYKUENHU-UHFFFAOYSA-N
  MISS  'PS-6': skip: no usable name and no IUPAC/SMILES
  MATCH 'SJF-0628' via cname: CID=146547699, InChIKey=MBCAVOCJJAQHHT-FGUOTCRGSA-N
  MATCH 'RC32' via cname: CID=156599864, InChIKey=XCSUEITWRRFFMN-LPIXFUNRSA-N
  MISS  'NP8': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MATCH 'd9A-2' via cname: CID=156726730, InChIKey=WMBSSRAFHKGIRA-UHFFFAOYSA-N
  MISS  'dTAG13': cname=0 results
  MISS  'dTAG7': cname=0 results
  MATCH 'MD13' via cname: CID=163342432, InChIKey=HAHDZDUOFHMMEA-UHFFFAOYSA-N
  MISS  'MD9': skip: no usable name and no IUPAC/SMILES
  MISS  'Compound 2': cname=0 results
  MISS  'CRBN_1b': cname=0 results
  MISS  'CRBN_1e': cname=0 results
  MATCH 'JMC-137' via cname: CID=168275983, InChIKey=HWEFEZUTECUWNS-IIWOMYBWSA-N
  MATCH 'macroPROTAC-1' via cname: CID=145704688, InChIKey=GMEHQGWGMMKWAX-NIQMDXQVSA-N
  MATCH 'IR-1' via cname: CID=168316234, InChIKey=AWOLTJZICWTLFS-AHDGVXFFSA-N
  MATCH 'QC-01–175' via cname: CID=139593563, InChIKey=NWTCZTAQSRLSCP-UHFFFAOYSA-N
  MISS  'RGC-01-05-18': cname=0 results
  MISS  'iRGC': cname=0 results
  MATCH 'VZ185' via cname: CID=138454768, InChIKey=ZAGCLFXBHOXXEN-JPTLTNPLSA-N
  MATCH 'dBRD9' via cname: CID=135397681, InChIKey=AIOCFZJGGGEWDK-UHFFFAOYSA-N
  MISS  'DDa-1': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MISS  'CDa-1': cname=0 results
  MATCH 'DT2216' via cname: CID=139331475, InChIKey=PXVFFBGSTYQHRO-REQIQPEASA-N
  MISS  'D3': skip: no usable name and no IUPAC/SMILES
  MISS  'D10': skip: no usable name and no IUPAC/SMILES
  MISS  'D12': skip: no usable name and no IUPAC/SMILES
  MISS  'D14': cname=0 results
  MISS  'D15': skip: no usable name and no IUPAC/SMILES
  MATCH 'dBET57' via cname: CID=118912822, InChIKey=CZRLOIDJCMKJHE-UXMRNZNESA-N
  MATCH 'A6' via SMILES: CID=166642468, InChIKey=FQLCLMHMOFLVSV-UHFFFAOYSA-N
  MISS  'XR-4': cname=0 results
  MISS  '2': skip: no usable name and no IUPAC/SMILES
  MISS  'KTX-335': cname=0 results
  MISS  'KTX-652': cname=0 results
  MISS  'KTX-978': cname=0 results
  MISS  'CRBN(BRAF)-24': cname=0 results
  MISS  'Cpd 1': skip: no usable name and no IUPAC/SMILES
  MISS  'B1-10J': cname=0 results
  MISS  'B1-10P': cname=0 results
  MISS  'B2-12P': cname=0 results
  MISS  'B1-10': cname=0 results
  MISS  'B2-12': cname=0 results
  MISS  'B2-14': cname=0 results
  MATCH 'A947' via cname: CID=139546336, InChIKey=QQVCUSPUMMUFTD-NCXNEFEISA-N
  MISS  'BTR2004': cname=0 results
  MISS  'FS-ARV-825': cname=0 results
  MATCH 'ARV-825' via cname: CID=92044400, InChIKey=RWLOGRLTDKDANT-TYIYNAFKSA-N

--- PubChem Results ---
Matched triples: 52/130
Standard_InChIKey filled: 150
IUPAC_Name filled: 71
SMILES filled: 129
Standard_InChIKey still missing: 135

In [10]:
output_path = os.path.join(data_dir, "260502_merged_protac_data_processed_cleaned_inchikey_pubchem_2nd.csv")
merged_cleaned_protac.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_protac.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_2nd/260502_merged_protac_data_processed_cleaned_inchikey_pubchem_2nd.csv
Shape: (668, 18)

### Add connectivity_key

In [11]:
merged_cleaned_protac = add_connectivity_key(merged_cleaned_protac)

In [12]:
merged_cleaned_protac

,DOI,Compound_Name,IUPAC_Name,SMILES,SMILES_Source,Degradation_Target,Recruiter,Assay,Cell_Line,DC50,DC50_units,DC50_h,Dmax,Dmax_h,Dmax_conc,Standard_InChIKey,Standard_InChIKey_Source,IUPAC_Name_Source,Connectivity_Key
0,10.1038/s42003-020-0868-6,1,NaN,NaN,<NA>,RIPK2,VHL,capillary-based immunoassay,THP-1,2.0,nM,18 h,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>
1,10.1038/s42003-020-0868-6,2,(S)-7-(2-(2-(2-(2-((4-(benzo[d]thiazol-5-ylami...,NaN,<NA>,RIPK2,IAP,capillary-based immunoassay,THP-1,0.40,nM,18 h,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>
2,10.1038/s42003-020-0868-6,3,(S)-14-((4-(Benzo[d]thiazol-5-ylamino)-6-(tert...,S1C=NC2=C1C=CC(=C2)NC2=CC=NC1=CC(=C(C=C21)S(=O...,OPSIN,RIPK2,cereblon,capillary-based immunoassay,THP-1,2.5,nM,18 h,NaN,NaN,NaN,BRZGXSNAXRPPFI-DHUJRADRSA-N,OPSIN,<NA>,BRZGXSNAXRPPFI
3,10.1038/s42003-020-0868-6,4,(S)-N-((S)-1-(1-(2-(4-(2-((6-(tert-Butylsulfon...,C(C)(C)(C)S(=O)(=O)C=1C=C2C(=NC=NC2=CC1OCCN1CC...,OPSIN,RIPK2,IAP,Simple Western (capillary-based) immunoassay,human PBMCs,12.6,nM,24 h,69.2,24 h,NaN,HZMQXNZSFFXKMT-LCPJFFRWSA-N,OPSIN,<NA>,HZMQXNZSFFXKMT
4,10.1038/s42003-020-0868-6,6,"5-(4-(3-((6-(tert-Butylsulfonyl)-4-((4,5-dimet...",C(C)(C)(C)S(=O)(=O)C=1C=C2C(=NC=NC2=CC1OCCCN1C...,OPSIN,RIPK2,IAP,Simple Western (capillary-based) immunoassay,human PBMCs,0.40,nM,24 h,94.3,24 h,NaN,CHNBEZLJAQUZEX-LFRONEFISA-N,OPSIN,<NA>,CHNBEZLJAQUZEX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
663,10.1101/gad.349717.122,BTR2004,NaN,NaN,<NA>,BRD3,KLHL20,Western blot densitometry,PC3,~87,nM,4,100,4,10 μM,<NA>,<NA>,<NA>,<NA>
664,10.1101/gad.349717.122,BTR2004,NaN,NaN,<NA>,BRD4,KLHL20,Western blot densitometry,PC3,~777,nM,4,100,4,10 μM,<NA>,<NA>,<NA>,<NA>
665,10.1039/d3cb00103b,FS-ARV-825,NaN,NaN,<NA>,GSPT1,CRBN,GFP/mCherry high-content imaging (Operetta),Flp293T cells stably expressing GFP-GSPT1domai...,~500,nM,5 h,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>
666,10.1039/d3cb00103b,ARV-825,"2-[(9S)-7-(4-chlorophenyl)-4,5,13-trimethyl-3-...",CC1=C(SC2=C1C(=N[C@H](C3=NN=C(N32)C)CC(=O)NC4=...,PUBCHEM,IKZF1,CRBN,HiBiT lytic luminescence assay,MOLT4 HiBiT-IKZF1 cells,26 ± 2,nM,24 h,~95,24 h,NaN,RWLOGRLTDKDANT-TYIYNAFKSA-N,PUBCHEM,PUBCHEM,RWLOGRLTDKDANT
667,10.1039/d3cb00103b,FS-ARV-825,NaN,NaN,<NA>,IKZF1,CRBN,HiBiT lytic luminescence assay,MOLT4 HiBiT-IKZF1 cells,200 ± 28,nM,24 h,~95,24 h,NaN,<NA>,<NA>,<NA>,<NA>

In [13]:
output_path = os.path.join(data_dir, "260502_merged_protac_data_processed_cleaned_inchikey_pubchem_ck_2nd.csv")
merged_cleaned_protac.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_protac.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_2nd/260502_merged_protac_data_processed_cleaned_inchikey_pubchem_ck_2nd.csv
Shape: (668, 19)

# Porcess Molecular Glues Extracted Data

In [2]:
import pandas as pd
import os

glue_path = '/Users/yaochenr/project/molecular_glue_extractor/output/results/260504_1500/data_processed.csv'
merged_glues = pd.read_csv(glue_path)
merged_glues.head()

,DOI,source,Compound_Name,IUPAC_Name,SMILES,Degradation_Target,Recruiter,Assay,Cell_Line,DC50,DC50_units,DC50_h,Dmax,Dmax_h,Dmax_conc
0,10.1038/s41467-022-28907-3,main_text,indisulam,NaN,NaN,RBM39,DCAF15,LC–MS-based global label-free proteomics,IMR-32,NaN,NaN,NaN,NaN,NaN,NaN
1,10.1038/s41467-022-28907-3,main_text,indisulam,NaN,NaN,RBM39,DCAF15,Western blot,IMR-32,NaN,NaN,NaN,NaN,NaN,NaN
2,10.1038/s41467-022-28907-3,main_text,indisulam,NaN,NaN,RBM39,DCAF15,Western blot,KELLY,NaN,NaN,NaN,NaN,NaN,NaN
3,10.1038/s41467-022-28907-3,main_text,E7820,NaN,NaN,RBM39,DCAF15,Western blot,KELLY,NaN,NaN,NaN,NaN,NaN,NaN
4,10.1002/mabi.202400427,main_text,PRO-Lin7,NaN,NaN,Lin28,CRBN,Western blot,PA-1,≈ 300,nM,NaN,75,NaN,1 µM

### Remove rows where DC50 & Dmax are both empty

In [3]:
merged_cleaned_glues = remove_empty_dc50_dmax(merged_glues)

Removed 183 rows where both DC50 and Dmax are empty
Shape: 424 -> 241

In [4]:
data_dir_glues = "/Users/yaochenr/project/molecular_glue_extractor/output/results/260504-glue-data-all-rep/data_2nd"
os.makedirs(data_dir_glues, exist_ok=True)
output_merged = os.path.join(data_dir_glues, "260504_merged_glue_data_processed_cleaned_2nd.csv")
merged_cleaned_glues.to_csv(output_merged, index=False)
print(f"Saved cleaned merged data to: {output_merged}")
print(f"Shape: {merged_cleaned_glues.shape}")

Saved cleaned merged data to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260504-glue-data-all-rep/data_2nd/260504_merged_glue_data_processed_cleaned_2nd.csv
Shape: (241, 15)

### Add Standard InChIKey via OPSIN

In [5]:
merged_cleaned_glues = add_inchikey_opsin(merged_cleaned_glues)

Rows with SMILES from paper: 32
Processed 50/241 rows...
Processed 200/241 rows...

Done! Success: 135, Failed: 46, Skipped (no IUPAC): 60
Standard_InChIKey filled: 135
SMILES from PAPER: 32
SMILES from OPSIN: 105
SMILES still missing: 104

--- Failed rows ---
{'row': 59, 'status': 404, 'DOI': '10.1038/s41467-025-58431-z', 'Compound_Name': '13', 'IUPAC_Name': "3-(1'-(cyclohexylmethyl)-6-oxo-6,8-dihydro-2H,7H-spiro[furo[2,3 e]isoindole-3,4'-piperidin]-7-yl)pip"}
{'row': 60, 'status': 404, 'DOI': '10.1038/s41467-025-58431-z', 'Compound_Name': '14', 'IUPAC_Name': "3-(6-oxo-1'-(pyridin-2-ylmethyl)-6,8-dihydro-2H,7H-spiro[furo[2,3 e]isoindole-3,4'-piperidin]-7-yl)p"}
{'row': 61, 'status': 404, 'DOI': '10.1038/s41467-025-58431-z', 'Compound_Name': '15', 'IUPAC_Name': "3-(6-oxo-1'-(thiophen-3-ylmethyl)-6,8-dihydro-2H,7H-spiro[furo[2,3 e]isoindole-3,4'-piperidin]-7-yl)"}
{'row': 63, 'status': 404, 'DOI': '10.1038/s41467-025-58431-z', 'Compound_Name': '7', 'IUPAC_Name': "3-(6'-oxo-4-phenoxy-6',8'-dihydro-2'H,7'H-spiro[cyclohexane-1,3' furo[2,3-e]isoindol]-7'-yl)piperidi"}
{'row': 65, 'status': 404, 'DOI': '10.1038/s41467-025-58431-z', 'Compound_Name': '9', 'IUPAC_Name': "3-(1-benzyl-6'-oxo-6',8'-dihydro-2'H,7'H-spiro[azepane-4,3' furo[2,3-e]isoindol]-7'-yl)piperidine-2,"}
{'row': 83, 'status': 404, 'DOI': '10.1186/s13045-024-01592-z', 'Compound_Name': 'MGD-28', 'IUPAC_Name': '4 - (4 - (4 - (2 - (2, 6 - oxygen generation of piperidine 2-3 - base) - 3 - methyl - 1 - - 1, 2, 3,'}
{'row': 84, 'status': 404, 'DOI': '10.1186/s13045-024-01592-z', 'Compound_Name': 'MGD-28', 'IUPAC_Name': '4 - (4 - (4 - (2 - (2, 6 - oxygen generation of piperidine 2-3 - base) - 3 - methyl - 1 - - 1, 2, 3,'}
{'row': 85, 'status': 404, 'DOI': '10.1186/s13045-024-01592-z', 'Compound_Name': 'MGD-28', 'IUPAC_Name': '4 - (4 - (4 - (2 - (2, 6 - oxygen generation of piperidine 2-3 - base) - 3 - methyl - 1 - - 1, 2, 3,'}
{'row': 86, 'status': 404, 'DOI': '10.1186/s13045-024-01592-z', 'Compound_Name': 'MGD-28', 'IUPAC_Name': '4 - (4 - (4 - (2 - (2, 6 - oxygen generation of piperidine 2-3 - base) - 3 - methyl - 1 - - 1, 2, 3,'}
{'row': 121, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS24', 'IUPAC_Name': '(R)-2-((6-((3-fluoro-4-(pyridin-2-yl)benzyl)amino)-9-isopropyl-9H-purin-2-yl)amino)butan-1-ol (DS24)'}
{'row': 122, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS25', 'IUPAC_Name': '(R)-2-((9-isopropyl-6-((4-(5-methylthiophen-2-yl)benzyl)amino)-9H-purin-2-yl)amino)butan-1-ol (DS25)'}
{'row': 123, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS28', 'IUPAC_Name': '(S)-2-((9-isopropyl-6-((4-(pyridin-2-yl)benzyl)amino)-9H-purin-2-yl)amino)butan-1-ol (DS28)'}
{'row': 124, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS29', 'IUPAC_Name': '(R)-2-((6-((3-(3-fluorophenyl)propyl)amino)-9-isopropyl-9H-purin-2-yl)amino)butan-1-ol (DS29)'}
{'row': 125, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS30', 'IUPAC_Name': '(R)-2-((9-isopropyl-6-((3-(m-tolyl)propyl)amino)-9H-purin-2-yl)amino)butan-1-ol (DS30)'}
{'row': 126, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS43', 'IUPAC_Name': '(R)-2-((6-(((1-(3-chlorophenyl)-1H-pyrazol-3-yl)methyl)amino)-9-isopropyl-9H-purin-2-yl)amino)butan-'}
{'row': 127, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS44', 'IUPAC_Name': '(R)-2-((9-isopropyl-6-((4-(pyridin-4-yl)benzyl)amino)-9H-purin-2-yl)amino)butan-1-ol (DS44)'}
{'row': 128, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS45', 'IUPAC_Name': '(R)-2-((9-isopropyl-6-((4-(pyridin-3-yl)benzyl)amino)-9H-purin-2-yl)amino)butan-1-ol (DS45)'}
{'row': 129, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS48', 'IUPAC_Name': 'N2-((3,5-dichloropyridin-4-yl)methyl)-9-isopropyl-N6-(4-(pyridin-2-yl)benzyl)-9H-purine-2,6-diamine '}
{'row': 130, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS50', 'IUPAC_Name': '2-((9-isopropyl-6-((4-(pyridin-2-yl)benzyl)amino)-9H-purin-2-yl)amino)-N-(2-methoxyphenethyl)acetami'}
{'row': 131, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS52', 'IUPAC_Name': 'N2-(2-(1H-pyrazol-4-yl)ethyl)-N6-(4-(pyridin-2-yl)benzyl)-9-isopropyl-9H-purine-2,6-diamine (DS52)'}
{'row': 132, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS53', 'IUPAC_Name': "(R)-2-((6-(([2,4'-bipyridin]-5-ylmethyl)amino)-9-isopropyl-9H-purin-2-yl)amino)butan-1-ol (DS53)"}
{'row': 133, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS57', 'IUPAC_Name': 'N2-(2-(1H-pyrazol-4-yl)ethyl)-N6-((5,6-dichloro-1H-benzo[d]imidazol-2-yl)methyl)-9-(1-methyl-1H-pyra'}
{'row': 134, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS58', 'IUPAC_Name': '(S)-N2-(2-(4-(benzyloxy)phenyl)-1-(4H-1,2,4-triazol-3-yl)ethyl)-9-isopropyl-N6-(4-(pyridin-2-yl)benz'}
{'row': 135, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS59', 'IUPAC_Name': '5-(((9-isopropyl-6-((4-(pyridin-2-yl)benzyl)amino)-9H-purin-2-yl)amino)methyl)-1,3-dimethyl-1H-pyraz'}
{'row': 136, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS61', 'IUPAC_Name': '(R)-2-((6-((4-(2-hydroxyethoxy)benzyl)amino)-9-isopropyl-9H-purin-2-yl)amino)butan-1-ol (DS61)'}
{'row': 137, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS64', 'IUPAC_Name': '(R)-2-((6-((4,5-difluoro-1H-benzo[d]imidazol-2-yl)methyl)amino)-9-isopropyl-9H-purin-2-yl)amino)buta'}
{'row': 138, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS65', 'IUPAC_Name': '(R)-2-((6-((3-(3,4-dichlorophenyl)propyl)amino)-9-isopropyl-9H-purin-2-yl)amino)butan-1-ol (DS65)'}
{'row': 139, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS66', 'IUPAC_Name': '(R)-2-((6-((3-(3,5-dimethylphenyl)propyl)amino)-9-isopropyl-9H-purin-2-yl)amino)butan-1-ol (DS66)'}
{'row': 140, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS67', 'IUPAC_Name': '(R)-2-((6-((3-(3-ethylphenyl)propyl)amino)-9-isopropyl-9H-purin-2-yl)amino)butan-1-ol (DS67)'}
{'row': 141, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS68', 'IUPAC_Name': '(R)-3-(3-((2-((1-hydroxybutan-2-yl)amino)-9-isopropyl-9H-purin-6-yl)amino)propyl)phenol (DS68)'}
{'row': 142, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS69', 'IUPAC_Name': '(R)-2-((9-isopropyl-6-((3-(6-methylpyridin-2-yl)propyl)amino)-9H-purin-2-yl)amino)butan-1-ol (DS69)'}
{'row': 143, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'WX3', 'IUPAC_Name': "(R)-6'-(((2-((1-hydroxybutan-2-yl)amino)-9-isopropyl-9H-purin-6-yl)amino)methyl)-[2,3' bipyridin]-2'"}
{'row': 144, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'WX4', 'IUPAC_Name': "(R)-2-((6-(((4-(1,3-dioxolan-2-yl)-[2,2'-bipyridin]-5-yl)methyl)amino)-9-isopropyl-9H-purin-2-yl)ami"}
{'row': 145, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS71', 'IUPAC_Name': '8-bromo-N-((4,5-difluoro-1H-benzo[d]imidazol-2-yl)methyl)-2-(4-methylpiperazin-1-yl)pyrazolo[1,5-a]['}
{'row': 146, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS72', 'IUPAC_Name': '8-bromo-N-((4,5-difluoro-1H-benzo[d]imidazol-2-yl)methyl)-2-morpholinopyrazolo[1,5-a][1,3,5]triazin-'}
{'row': 147, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS73', 'IUPAC_Name': '8-bromo-N-((5,6-dimethyl-1H-benzo[d]imidazol-2-yl)methyl)-2-(4-methylpiperazin-1-yl)pyrazolo[1,5-a]['}
{'row': 148, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS74', 'IUPAC_Name': 'N-((5,6-dichloro-1H-benzo[d]imidazol-2-yl)methyl)-8-(1-methyl-1H-pyrazol-4-yl)-2-morpholinopyrazolo['}
{'row': 168, 'status': 404, 'DOI': '10.1038/s41589-024-01668-4', 'Compound_Name': 'GNE11', 'IUPAC_Name': 'tert-butyl (S)-2-(4-(4-(3-aminoprop-1-yn-1-yl)phenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]triazol'}
{'row': 169, 'status': 404, 'DOI': '10.1038/s41589-024-01668-4', 'Compound_Name': 'TMX1', 'IUPAC_Name': 'tert-butyl (S,E)-2-(2,3,9-trimethyl-4-(4-(3-oxoprop-1-en-1-yl)phenyl)-6H-thieno[3,2 f][1,2,4]triazol'}
{'row': 170, 'status': 404, 'DOI': '10.1038/s41589-024-01668-4', 'Compound_Name': 'MMH1', 'IUPAC_Name': 'tert-butyl (S)-2-(4-(4-acrylamidophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]triazolo[4,3-a][1,4]'}
{'row': 171, 'status': 404, 'DOI': '10.1038/s41589-024-01668-4', 'Compound_Name': 'MMH2', 'IUPAC_Name': 'tert-butyl (S)-2-(2,3,9-trimethyl-4-(4-(vinylsulfonamido)phenyl)-6H-thieno[3,2 f][1,2,4]triazolo[4,3'}
{'row': 202, 'status': 404, 'DOI': '10.1038/s41467-024-50642-0', 'Compound_Name': 'LL-K12-7', 'IUPAC_Name': 'N-(1-(6-(((5,6-dichloro-1H-benzo[d]midazole-2-yl)methyl)amino)-9-ethyl-9H-purin-2 yl)piperidin-4-yl)'}
{'row': 203, 'status': 404, 'DOI': '10.1038/s41467-024-50642-0', 'Compound_Name': 'LL-K12-8', 'IUPAC_Name': '2-butoxy-N-((5,6-dichloro-1H-benzo[d]midazole-2-yl)methyl)-9-ethyl-9H-purin-6-amine'}
{'row': 204, 'status': 404, 'DOI': '10.1038/s41467-024-50642-0', 'Compound_Name': 'LL-K12-9', 'IUPAC_Name': 'N-((5,6-dichloro-1H-benzo[d]midazole-2-yl)methyl)-2-(5,6-dihydro-[1,2,4]triazolo [1,5 a]pyrazin-7(8H'}
{'row': 210, 'status': 404, 'DOI': '10.1038/s41467-024-50642-0', 'Compound_Name': 'LL-K12-15', 'IUPAC_Name': 'N-((5,6-dichloro-1H-benzo[d]imidazol-2-yl)methyl)-9-ethyl-2-(4-(pyridin-3-ylmethyl) napiperazin-1-yl'}
{'row': 214, 'status': 404, 'DOI': '10.1038/s41467-024-50642-0', 'Compound_Name': 'LL-K12-19', 'IUPAC_Name': 'N-((6,7-difluoro-1H-benzo[d]imidazol-2-yl)methyl)-2-(5,6-dihydro-[1,2,4]triazolo [1,5 a]pyrazin-7(8H'}

In [6]:
output_path = os.path.join(data_dir_glues, "260504_merged_glue_data_processed_cleaned_inchikey_2nd.csv")
merged_cleaned_glues.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_glues.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260504-glue-data-all-rep/data_2nd/260504_merged_glue_data_processed_cleaned_inchikey_2nd.csv
Shape: (241, 18)

### PubChem Search

In [7]:
merged_cleaned_glues = pubchem_search(merged_cleaned_glues)

Rows missing Standard_InChIKey: 106 (78 unique (cname, iupac, smiles) triples)
  MISS  'PRO-Lin7': cname=0 results
  MISS  'MG-Lin1': cname=0 results
  MATCH 'lenalidomide' via cname: CID=216326, InChIKey=GOTYRUGSSMKFNF-UHFFFAOYSA-N
  MATCH 'dBET57' via cname: CID=118912822, InChIKey=CZRLOIDJCMKJHE-UXMRNZNESA-N
  MATCH 'A6' via SMILES: CID=166642468, InChIKey=FQLCLMHMOFLVSV-UHFFFAOYSA-N
  MISS  '13-7': skip: no usable name and no IUPAC/SMILES
  MATCH 'DKY709' via cname: CID=137519326, InChIKey=OMISHRJQMYQPMG-UHFFFAOYSA-N
  MISS  '13': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MISS  '14': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MISS  '15': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MISS  '7': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MISS  '9': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MATCH 'pomalidomide' via cname: CID=134780, InChIKey=UVSMNLNDYGZFPF-UHFFFAOYSA-N
  MISS  'iDeg-6': cname=0 results
  MATCH 'MGD-28' via cname: CID=172871692, InChIKey=JICHBFQDRLGJTM-UHFFFAOYSA-N
  MATCH 'PT-179' via cname: CID=163294079, InChIKey=CCCSRHUSXCBFJZ-UHFFFAOYSA-N
  MATCH 'Pomalidomide' via cname: CID=134780, InChIKey=UVSMNLNDYGZFPF-UHFFFAOYSA-N
  MATCH 'SR-4835' via cname: CID=139600338, InChIKey=FSELUFUYNUNZKD-UHFFFAOYSA-N
  MISS  'CU-0906': cname=0 results
  MISS  'VNPP433-3β': cname=0 results
  MISS  'LC-04–075': cname=0 results
  MISS  'LC-04–087': cname=0 results
  MISS  'LC-04–081': cname=0 results
  MISS  'LC-04–077': cname=0 results
  MISS  'LC-04–155': cname=0 results
  MISS  'LC-04–162': cname=0 results
  MISS  'CR8': cname=0 results
  MATCH 'DS02' via cname: CID=168499469, InChIKey=KLBKESYFUKKKSS-LJQANCHMSA-N
  MATCH 'DS24' via cname: CID=168477809, InChIKey=DZJLJYVQLLFULK-QGZVFWFLSA-N
  MATCH 'DS25' via cname: CID=168499473, InChIKey=IGJPGKABXPANSO-LJQANCHMSA-N
  MATCH 'DS28' via cname: CID=25211051, InChIKey=HOCBJBNQIQQQGT-IBGZPJMESA-N
  MATCH 'DS29' via cname: CID=168499482, InChIKey=CQVNQDCOBDXVMZ-QGZVFWFLSA-N
  MATCH 'DS30' via cname: CID=168477823, InChIKey=IAQVCGQJJMTIMM-GOSISDBHSA-N
  MATCH 'DS43' via cname: CID=168477813, InChIKey=XQOCHZAMFJBROM-MRXNPFEDSA-N
  MATCH 'DS44' via cname: CID=9867425, InChIKey=UQRBOMYWGJFNEB-HXUWFJFHSA-N
  MATCH 'DS45' via cname: CID=9802824, InChIKey=AXLQKORZTHWACD-HXUWFJFHSA-N
  MATCH 'DS48' via cname: CID=168499486, InChIKey=YENZFYNZBFLBNQ-UHFFFAOYSA-N
  MATCH 'DS50' via cname: CID=168477816, InChIKey=FAZBCDJEMSESAO-UHFFFAOYSA-N
  MATCH 'DS52' via cname: CID=168499487, InChIKey=ZPVLGUHALYPMCR-UHFFFAOYSA-N
  MATCH 'DS53' via cname: CID=168499484, InChIKey=NPMNSMOOUPMFMV-GOSISDBHSA-N
  MATCH 'DS57' via cname: CID=168499492, InChIKey=DKIVKUGXNDYWCX-UHFFFAOYSA-N
  MATCH 'DS58' via cname: CID=168499489, InChIKey=OJCJKFBTXCLERR-UHFFFAOYSA-N
  MATCH 'DS59' via cname: CID=168477810, InChIKey=DCNMIIRVWOSZDG-UHFFFAOYSA-N
  MATCH 'DS61' via cname: CID=168477812, InChIKey=AFLLXNOWMGJTAA-MRXNPFEDSA-N
  MATCH 'DS64' via cname: CID=168499496, InChIKey=DCTODZNTFHJKGP-LLVKDONJSA-N
  MATCH 'DS65' via cname: CID=168499479, InChIKey=OLTUKTKUEARKCY-OAHLLOKOSA-N
  MATCH 'DS66' via cname: CID=168499478, InChIKey=CWXUALXYQXQCPS-LJQANCHMSA-N
  MATCH 'DS67' via cname: CID=168499480, InChIKey=ZELMGONKTIAQJA-LJQANCHMSA-N
  MATCH 'DS68' via cname: CID=168499483, InChIKey=WREYDFZOQPABSD-MRXNPFEDSA-N
  MATCH 'DS69' via cname: CID=168499481, InChIKey=IYNJPMYEAQNCBL-MRXNPFEDSA-N
  MATCH 'WX3' via cname: CID=168477817, InChIKey=ZZMGLCCXIBNSGN-OAHLLOKOSA-N
  MISS  'WX4': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MATCH 'DS71' via cname: CID=156482117, InChIKey=PPZYKPKJVAUJRL-UHFFFAOYSA-N
  MATCH 'DS72' via cname: CID=156473215, InChIKey=OQEZGFYMQUIYPA-UHFFFAOYSA-N
  MATCH 'DS73' via cname: CID=156482229, InChIKey=PGDRKKXMPSPTSV-UHFFFAOYSA-N
  MATCH 'DS74' via cname: CID=156473213, InChIKey=RSUMIRUUOWUKDK-UHFFFAOYSA-N
  MISS  '21195': skip: no usable name and no IUPAC/SMILES
  MISS  '919278': skip: no usable name and no IUPAC/SMILES
  MATCH 'dCeMM2' via cname: CID=5286209, InChIKey=VFWVTIHYVUKNGR-UHFFFAOYSA-N
  MATCH 'dCeMM4' via cname: CID=53546112, InChIKey=BPWZJVKIVHVVHP-UHFFFAOYSA-N
  MATCH 'HQ461' via cname: CID=49677967, InChIKey=QMRBCNQCRMTXBE-UHFFFAOYSA-N
  MISS  'Z11': cname=0 results
  MISS  'Z12': cname=0 results
  MISS  'Z10': cname=0 results
  MATCH 'DS47' via cname: CID=168499490, InChIKey=LVVKHGPMCAECNF-CONSDPRKSA-N
  MISS  'DS_CR8': cname=0 results
  MATCH 'GNE11' via cname: CID=146478891, InChIKey=PMSPBUOYDPYDPF-FQEVSTJZSA-N
  MATCH 'TMX1' via cname: CID=168264924, InChIKey=SJISOGWQGIVAGX-DUIUGDAFSA-N
  MATCH 'MMH1' via cname: CID=169450066, InChIKey=AEEGEVCKDJFBRN-IBGZPJMESA-N
  MATCH 'MMH2' via cname: CID=169450067, InChIKey=FZRRESXAODIMQN-IBGZPJMESA-N
  MISS  '5': skip: no usable name and no IUPAC/SMILES
  MISS  '4': skip: no usable name and no IUPAC/SMILES
  MATCH 'CC-90009' via cname: CID=118647211, InChIKey=PWBHUSLMHZLGRN-UHFFFAOYSA-N
  MISS  'LL-K12-7': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MISS  'LL-K12-8': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MISS  'LL-K12-9': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MISS  'LL-K12-15': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MISS  'LL-K12-19': cname=0 results; IUPAC=0 results, SMILES=no SMILES

--- PubChem Results ---
Matched triples: 46/78
Standard_InChIKey filled: 71
IUPAC_Name filled: 36
SMILES filled: 69
Standard_InChIKey still missing: 35

In [8]:
output_path = os.path.join(data_dir_glues, "260504_merged_glue_data_processed_cleaned_inchikey_pubchem_2nd.csv")
merged_cleaned_glues.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_glues.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260504-glue-data-all-rep/data_2nd/260504_merged_glue_data_processed_cleaned_inchikey_pubchem_2nd.csv
Shape: (241, 19)

### Add connectivity_key

In [9]:
merged_cleaned_glues = add_connectivity_key(merged_cleaned_glues)

In [10]:
merged_cleaned_glues[['Compound_Name', 'Standard_InChIKey', 'Connectivity_Key']]

    Compound_Name            Standard_InChIKey Connectivity_Key
0        PRO-Lin7                         <NA>             <NA>
1         MG-Lin1                         <NA>             <NA>
2              5a  MSHTVRYXGFREAN-UHFFFAOYSA-N   MSHTVRYXGFREAN
3              7d  QRQMHYISDDHZBY-UHFFFAOYSA-N   QRQMHYISDDHZBY
4              7f  NSEUGMATEWSNTO-UHFFFAOYSA-N   NSEUGMATEWSNTO
..            ...                          ...              ...
236     CCT373566  GSGDUDAFETZSPM-IATAILRESA-N   GSGDUDAFETZSPM
237     CCT373566  GSGDUDAFETZSPM-IATAILRESA-N   GSGDUDAFETZSPM
238     CCT373566  GSGDUDAFETZSPM-IATAILRESA-N   GSGDUDAFETZSPM
239     CCT373567  GSGDUDAFETZSPM-DHZVRSILSA-N   GSGDUDAFETZSPM
240     CCT373567  GSGDUDAFETZSPM-DHZVRSILSA-N   GSGDUDAFETZSPM

[241 rows x 3 columns]

In [11]:
output_path = os.path.join(data_dir_glues, "260504_merged_glue_data_processed_cleaned_inchikey_pubchem_ck_2nd.csv")
merged_cleaned_glues.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_glues.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260504-glue-data-all-rep/data_2nd/260504_merged_glue_data_processed_cleaned_inchikey_pubchem_ck_2nd.csv
Shape: (241, 20)