**Molecular glue and PROTACs LLM prediction vs. ground truth for the 3rd run**

# Processing Functions

In [ ]:
import requests
import time
from urllib.parse import quote
import pubchempy as pcp


OPSIN_BASE = "https://www.ebi.ac.uk/opsin/ws"
_DASH_CHARS = "‐‑‒–—―−﹣－"
_DASH_TRANS = str.maketrans({c: "-" for c in _DASH_CHARS})


def _normalize_dashes(s):
    if not isinstance(s, str):
        return s
    return s.translate(_DASH_TRANS)


PUBCHEM_BLOCKLIST = {
    "Mei", "Po", "Le",
    "LC-4", "LC-6",
    "D10", "D12", "D15",
    "A13", "13b",
    "SC5", "SC7", "SC10",
    "DBt-10",
    "PS-6",
    "MD9",
    "Cpd 1",
}


def remove_empty_dc50_dmax(df):
    before = len(df)
    cleaned = df.dropna(subset=["DC50", "Dmax"], how="all")
    cleaned = cleaned[~(
        cleaned["DC50"].astype(str).str.strip().isin(["", "nan"])
        & cleaned["Dmax"].astype(str).str.strip().isin(["", "nan"])
    )]
    cleaned = cleaned.reset_index(drop=True)
    after = len(cleaned)
    print(f"Removed {before - after} rows where both DC50 and Dmax are empty")
    print(f"Shape: {before} -> {after}")
    return cleaned


def add_inchikey_opsin(df, sleep_sec=0.1):
    df = df.copy()
    df["Standard_InChIKey"] = pd.NA
    df["Standard_InChIKey_Source"] = pd.NA
    if "SMILES_Source" not in df.columns:
        df["SMILES_Source"] = pd.NA

    has_smiles = df["SMILES"].notna() & (df["SMILES"].astype(str).str.strip() != "")
    df.loc[has_smiles, "SMILES_Source"] = "PAPER"
    print(f"Rows with SMILES from paper: {has_smiles.sum()}")

    success, fail, skip = 0, 0, 0
    failed_rows = []

    for idx, row in df.iterrows():
        iupac = row["IUPAC_Name"]
        if pd.isna(iupac) or str(iupac).strip() == "":
            skip += 1
            continue

        url = f"{OPSIN_BASE}/{quote(str(iupac).strip(), safe='')}.json"
        try:
            resp = requests.get(url, timeout=30)
            if resp.status_code == 200:
                data = resp.json()
                inchikey = data.get("stdinchikey")
                smiles = data.get("smiles")
                if inchikey:
                    df.at[idx, "Standard_InChIKey"] = inchikey
                    df.at[idx, "Standard_InChIKey_Source"] = "OPSIN"
                if not has_smiles[idx] and smiles:
                    df.at[idx, "SMILES"] = smiles
                    df.at[idx, "SMILES_Source"] = "OPSIN"
                success += 1
            else:
                failed_rows.append({"row": idx, "status": resp.status_code, "DOI": row["DOI"], "Compound_Name": row["Compound_Name"], "IUPAC_Name": str(iupac)[:100]})
                fail += 1
        except Exception as e:
            failed_rows.append({"row": idx, "error": str(e), "DOI": row["DOI"], "Compound_Name": row["Compound_Name"], "IUPAC_Name": str(iupac)[:100]})
            fail += 1

        if (idx + 1) % 50 == 0:
            print(f"Processed {idx + 1}/{len(df)} rows...")
        time.sleep(sleep_sec)

    cols = list(df.columns)
    smiles_idx = cols.index("SMILES")
    cols.remove("SMILES_Source")
    cols.insert(smiles_idx + 1, "SMILES_Source")
    df = df[cols]

    print(f"\nDone! Success: {success}, Failed: {fail}, Skipped (no IUPAC): {skip}")
    print(f"Standard_InChIKey filled: {df['Standard_InChIKey'].notna().sum()}")
    print(f"SMILES from PAPER: {(df['SMILES_Source'] == 'PAPER').sum()}")
    print(f"SMILES from OPSIN: {(df['SMILES_Source'] == 'OPSIN').sum()}")
    print(f"SMILES still missing: {df['SMILES'].isna().sum()}")
    if failed_rows:
        print(f"\n--- Failed rows ---")
        for fr in failed_rows:
            print(fr)
    return df


def pubchem_search(df, sleep_sec=0.3, blocklist=None, min_name_length=3):
    """Fill Standard_InChIKey (and IUPAC_Name / SMILES if missing) via PubChem.
    """
    df = df.copy()
    if blocklist is None:
        blocklist = PUBCHEM_BLOCKLIST

    def has_value(v):
        return pd.notna(v) and str(v).strip() != "" and str(v).strip().lower() != "nan"

    def is_numeric_name(s):
        return s.replace(".", "").replace("-", "").isdigit()

    def cname_usable(c):
        if not c:
            return False
        if c in blocklist or _normalize_dashes(c) in blocklist:
            return False
        if is_numeric_name(c):
            return False
        if len(c) < min_name_length:
            return False
        return True

    def search_name_with_synonym(raw_query):
        query = _normalize_dashes(raw_query).strip()
        if not query:
            return None, "empty after normalization"
        try:
            compounds = pcp.get_compounds(query, "name")
            if not compounds:
                return None, "0 results"
            top = compounds[0]
            syn_url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/{top.cid}/synonyms/JSON"
            syn_resp = requests.get(syn_url, timeout=30)
            if syn_resp.status_code != 200:
                return None, f"synonyms HTTP {syn_resp.status_code} (CID={top.cid})"
            syns = syn_resp.json()["InformationList"]["Information"][0]["Synonym"]
            q_cmp = query.lower()
            if not any(_normalize_dashes(s).lower() == q_cmp for s in syns):
                return None, f"not in synonyms (CID={top.cid})"
            return {"cid": top.cid, "iupac_name": top.iupac_name,
                    "smiles": top.smiles, "inchikey": top.inchikey}, "ok"
        except Exception as e:
            return None, f"error: {e}"

    def search_smiles(query):
        try:
            compounds = pcp.get_compounds(query, "smiles")
            if not compounds:
                return None, "0 results"
            top = compounds[0]
            return {"cid": top.cid, "iupac_name": top.iupac_name,
                    "smiles": top.smiles, "inchikey": top.inchikey}, "ok"
        except Exception as e:
            return None, f"error: {e}"

    def chem_search(iupac, smiles):
        if iupac:
            r, reason = search_name_with_synonym(iupac)
            time.sleep(sleep_sec)
            if r:
                return r, "IUPAC", reason
            iupac_reason = reason
        else:
            iupac_reason = "no IUPAC"
        if smiles:
            r, reason = search_smiles(smiles)
            time.sleep(sleep_sec)
            if r:
                return r, "SMILES", reason
            smiles_reason = reason
        else:
            smiles_reason = "no SMILES"
        return None, None, f"IUPAC={iupac_reason}, SMILES={smiles_reason}"

    for col in ("IUPAC_Name_Source", "Standard_InChIKey",
                "Standard_InChIKey_Source", "SMILES_Source"):
        if col not in df.columns:
            df[col] = pd.NA

    needs_key = df["Standard_InChIKey"].isna() | (df["Standard_InChIKey"].astype(str).str.strip() == "")
    to_search = df[needs_key].index

    queries = {}
    for idx in to_search:
        cname = str(df.at[idx, "Compound_Name"]).strip() if has_value(df.at[idx, "Compound_Name"]) else ""
        iupac = str(df.at[idx, "IUPAC_Name"]).strip()    if has_value(df.at[idx, "IUPAC_Name"])    else ""
        smi   = str(df.at[idx, "SMILES"]).strip()        if has_value(df.at[idx, "SMILES"])        else ""
        queries.setdefault((cname, iupac, smi), []).append(idx)

    print(f"Rows missing Standard_InChIKey: {len(to_search)} ({len(queries)} unique (cname, iupac, smiles) triples)")

    def short(s, n=40):
        return (s[:n] + "...") if s and len(s) > n else s

    cache = {}
    for (cname, iupac, smi), idxs in queries.items():
        usable_c = cname_usable(cname)
        has_chem = bool(iupac) or bool(smi)
        cs = short(cname) if cname else "(no cname)"

        result, method, reason = None, None, ""

        if usable_c and not has_chem:
            r, reason_c = search_name_with_synonym(cname)
            time.sleep(sleep_sec)
            if r:
                result, method, reason = r, "cname", reason_c
            else:
                reason = f"cname={reason_c}"
        elif usable_c and has_chem:
            r, reason_c = search_name_with_synonym(cname)
            time.sleep(sleep_sec)
            if r:
                result, method, reason = r, "cname", reason_c
            else:
                result, method, reason_chem = chem_search(iupac, smi)
                reason = f"cname={reason_c}; {reason_chem}" if not result else f"after cname miss: {reason_chem}"
        elif not usable_c and has_chem:
            result, method, reason_chem = chem_search(iupac, smi)
            reason = f"cname unusable; {reason_chem}"
        else:
            reason = "skip: no usable name and no IUPAC/SMILES"

        cache[(cname, iupac, smi)] = result

        if result:
            print(f"  MATCH '{cs}' via {method}: CID={result['cid']}, InChIKey={result['inchikey']}")
        else:
            print(f"  MISS  '{cs}': {reason}")

    filled_key = filled_iupac = filled_smi = 0
    for (cname, iupac, smi), idxs in queries.items():
        result = cache[(cname, iupac, smi)]
        if result is None:
            continue
        for idx in idxs:
            if result["inchikey"]:
                df.at[idx, "Standard_InChIKey"] = result["inchikey"]
                df.at[idx, "Standard_InChIKey_Source"] = "PUBCHEM"
                filled_key += 1
            if not has_value(df.at[idx, "IUPAC_Name"]) and result.get("iupac_name"):
                df.at[idx, "IUPAC_Name"] = result["iupac_name"]
                df.at[idx, "IUPAC_Name_Source"] = "PUBCHEM"
                filled_iupac += 1
            if not has_value(df.at[idx, "SMILES"]) and result.get("smiles"):
                df.at[idx, "SMILES"] = result["smiles"]
                df.at[idx, "SMILES_Source"] = "PUBCHEM"
                filled_smi += 1

    matched = sum(1 for v in cache.values() if v is not None)
    print(f"\n--- PubChem Results ---")
    print(f"Matched triples: {matched}/{len(queries)}")
    print(f"Standard_InChIKey filled: {filled_key}")
    print(f"IUPAC_Name filled: {filled_iupac}")
    print(f"SMILES filled: {filled_smi}")
    print(f"Standard_InChIKey still missing: {(df['Standard_InChIKey'].isna() | (df['Standard_InChIKey'].astype(str).str.strip() == '')).sum()}")
    return df

def add_connectivity_key(df):
    if 'Standard_InChIKey' in df.columns:
        df['Connectivity_Key'] = df['Standard_InChIKey'].str[:14]
    return df

# Porcess PROTACs Extracted Data

In [2]:
import pandas as pd
import os

protac_path = '/Users/yaochenr/project/molecular_glue_extractor/output/results/260502_0508/data_processed.csv'
merged_protacs = pd.read_csv(protac_path)
merged_protacs.head()

,DOI,source,Compound_Name,IUPAC_Name,SMILES,Degradation_Target,Recruiter,Assay,Cell_Line,DC50,DC50_units,DC50_h,Dmax,Dmax_h,Dmax_conc
0,10.1021/acscentsci.0c00411,supplementary_oc0c00411_si_001.md,LC-2,"(2S,4R)-1-((S)-2-(3-(3-((S)-2-(((7-(8-chlorona...",NaN,KRASG12C,VHL,immunoblotting,NCI-H2030,590.0 ± 200.0,nM,24,~80,24,2.5 μM
1,10.1021/acscentsci.0c00411,supplementary_oc0c00411_si_001.md,LC-2,"(2S,4R)-1-((S)-2-(3-(3-((S)-2-(((7-(8-chlorona...",NaN,KRASG12C,VHL,immunoblotting,MIA PaCa-2,320.0 ± 80.0,nM,24,~75,24,NaN
2,10.1021/acscentsci.0c00411,supplementary_oc0c00411_si_001.md,LC-2,"(2S,4R)-1-((S)-2-(3-(3-((S)-2-(((7-(8-chlorona...",NaN,KRASG12C,VHL,immunoblotting,SW1573,760.0 ± 300.0,nM,24,~90,24,NaN
3,10.1021/acscentsci.0c00411,supplementary_oc0c00411_si_001.md,LC-2,"(2S,4R)-1-((S)-2-(3-(3-((S)-2-(((7-(8-chlorona...",NaN,KRASG12C,VHL,immunoblotting,NCI-H23,250.0 ± 80.0,nM,24,~90,24,NaN
4,10.1021/acscentsci.0c00411,supplementary_oc0c00411_si_001.md,LC-2,"(2S,4R)-1-((S)-2-(3-(3-((S)-2-(((7-(8-chlorona...",NaN,KRASG12C,VHL,immunoblotting,NCI-H358,520.0 ± 300.0,nM,24,~40,24,NaN

In [4]:
data_dir = "/Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_3rd"
os.makedirs(data_dir, exist_ok=True)
output_path = os.path.join(data_dir, "260502_merged_protac_data_processed_3rd.csv")
merged_protacs.to_csv(output_path, index=False)
print(f"Saved merged data to: {output_path}")
print(f"Shape: {merged_protacs.shape}")

Saved merged data to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_3rd/260502_merged_protac_data_processed_3rd.csv
Shape: (809, 15)

### Remove rows where DC50 & Dmax are both empty

In [6]:
merged_cleaned_protac = remove_empty_dc50_dmax(merged_protacs)

Removed 115 rows where both DC50 and Dmax are empty
Shape: 809 -> 694

In [ ]:
output_merged = os.path.join(data_dir, "260502_merged_protac_data_processed_cleaned_3rd.csv")
merged_cleaned_protac.to_csv(output_merged, index=False)
print(f"Saved cleaned merged data to: {output_merged}")
print(f"Shape: {merged_cleaned_protac.shape}")

Saved cleaned merged data to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_3rd/260502_merged_protac_data_processed_cleaned_3rd.csv
Shape: (694, 15)

### Add Standard InChIKey via OPSIN

In [8]:
merged_cleaned_protac = add_inchikey_opsin(merged_cleaned_protac)

Rows with SMILES from paper: 126
Processed 150/694 rows...
Processed 300/694 rows...
Processed 450/694 rows...

Done! Success: 387, Failed: 101, Skipped (no IUPAC): 206
Standard_InChIKey filled: 387
SMILES from PAPER: 126
SMILES from OPSIN: 282
SMILES still missing: 286

--- Failed rows ---
{'row': 20, 'status': 404, 'DOI': '10.1038/s41467-018-08027-7', 'Compound_Name': 'SJFα', 'IUPAC_Name': 'N-(3-Fluoro-4-((7-(4-(4-(2-(((S)-1-((2S,4R)-4-hydroxy-2-((4-(4-methylthiazol-5-yl)benzyl) carbamoyl)'}
{'row': 21, 'status': 404, 'DOI': '10.1038/s41467-018-08027-7', 'Compound_Name': 'SJFα', 'IUPAC_Name': 'N-(3-Fluoro-4-((7-(4-(4-(2-(((S)-1-((2S,4R)-4-hydroxy-2-((4-(4-methylthiazol-5-yl)benzyl) carbamoyl)'}
{'row': 25, 'status': 404, 'DOI': '10.1038/s41467-018-08027-7', 'Compound_Name': 'SJF-6690', 'IUPAC_Name': 'N-(3-Fluoro-4-((7-(2-(3-(((S)-1-((2S,4R)-4-hydroxy-2-((4-(4-methylthiazol-5-yl)benzyl) carbamoyl)pyr'}
{'row': 26, 'status': 404, 'DOI': '10.1038/s41467-018-08027-7', 'Compound_Name': 'SJF-6690', 'IUPAC_Name': 'N-(3-Fluoro-4-((7-(2-(3-(((S)-1-((2S,4R)-4-hydroxy-2-((4-(4-methylthiazol-5-yl)benzyl) carbamoyl)pyr'}
{'row': 30, 'status': 404, 'DOI': '10.1038/s41467-018-08027-7', 'Compound_Name': 'SJF-6677', 'IUPAC_Name': 'N-(3-fluoro-4-((7-(4-(4-(2-(((2S,4R)-4-hydroxy-1-((S)-3-methyl-2-(1-oxoisoindolin-2 yl)butano -yl)py'}
{'row': 31, 'status': 404, 'DOI': '10.1038/s41467-018-08027-7', 'Compound_Name': 'SJF-6677', 'IUPAC_Name': 'N-(3-fluoro-4-((7-(4-(4-(2-(((2S,4R)-4-hydroxy-1-((S)-3-methyl-2-(1-oxoisoindolin-2 yl)butano -yl)py'}
{'row': 36, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 37, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 38, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 39, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 40, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 41, 'status': 404, 'DOI': '10.1038/s41467-021-21159-7', 'Compound_Name': 'SJF-0628', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(4-(4-(3-(2,6-difluoro-3-(propylsulfonamido)benzoyl)-1H-pyrrolo[2,3 b]pyridin-5-'}
{'row': 42, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15a', 'IUPAC_Name': '(2R,3R,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 43, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15a', 'IUPAC_Name': '(2R,3R,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 44, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15a', 'IUPAC_Name': '(2R,3R,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 45, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15b', 'IUPAC_Name': '(2R,3S,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 46, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15b', 'IUPAC_Name': '(2R,3S,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 47, 'status': 404, 'DOI': '10.1021/jacs.8b05807', 'Compound_Name': '15b', 'IUPAC_Name': '(2R,3S,4S)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]t'}
{'row': 51, 'status': 404, 'DOI': '10.1007/s13238-018-0602-z', 'Compound_Name': 'NP8', 'IUPAC_Name': '4-((1-(4-(1-(2-(2-(2-((2-(2,6-dioxopiperidin-3-yl)-1,3-dioxoisoindolin-4-yl)amino)eth oxy)etoxy)ethy'}
{'row': 64, 'status': 404, 'DOI': '10.1080/14756366.2022.2062338', 'Compound_Name': '16', 'IUPAC_Name': 'N-(2-(2, 6-dioxopiperidin-3-yl)-1,3-dioxoisoindolin-4-yl)-2-(2-(2-(2-(4-methyl-3-oxo-3, 4-dihydroqui'}
{'row': 67, 'status': 404, 'DOI': '10.1038/s42003-020-0868-6', 'Compound_Name': '2', 'IUPAC_Name': '(S)-7-(2-(2-(2-(2-((4-(benzo[d]thiazol-5-ylamino)-6-(tert-butylsulfonyl)quinolin-7-yl)oxy)ethoxy)eth'}
{'row': 117, 'status': 404, 'DOI': '10.1021/acschembio.5b00216', 'Compound_Name': 'MZ1', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(tert-butyl)-17-((S)-4-(4-chlorophenyl)-2,3,9-trimethyl-6H-thieno[3,2 f][1,2,4]tria'}
{'row': 137, 'status': 404, 'DOI': '10.1016/j.apsb.2020.11.022', 'Compound_Name': '11a', 'IUPAC_Name': 'N,N -(((Oxybis(ethane-2,1-diyl))bis(oxy))bis(ethane-2,1-diyl))bis(2-(4-(2-(4-(tert-butyl)-2-ethoxyph'}
{'row': 206, 'status': 404, 'DOI': '10.1021/jacsau.3c00228', 'Compound_Name': '21', 'IUPAC_Name': '(*R*)-2-((2*S*,3*R*)-3-amino-2-hydroxy-4-phenylbutanamido)-*N*-(2-(2-(2-(2-(4-(((2*S*,4*S*,11b*R*)-9'}
{'row': 231, 'status': 404, 'DOI': '10.1021/jacs.9b13907', 'Compound_Name': 'RC-3', 'IUPAC_Name': '18-((S)-3-(4-amino-3-(4-phenoxyphenyl)-1H-pyrazolo[3,4-d]pyrimidin-1 carbonyl)-1-((2-(2,6-dioxopiper'}
{'row': 234, 'status': 404, 'DOI': '10.1021/jacs.9b13907', 'Compound_Name': 'RC-2', 'IUPAC_Name': '(Z)-18-((S)-3-(4-amino-3-(4-phenoxyphenyl)-1H-pyrazolo[3,4-d]pyrimidin-1 carbonyl)-1-((2-(2,6-dioxop'}
{'row': 235, 'status': 404, 'DOI': '10.1021/jacs.9b13907', 'Compound_Name': 'RC-3', 'IUPAC_Name': '18-((S)-3-(4-amino-3-(4-phenoxyphenyl)-1H-pyrazolo[3,4-d]pyrimidin-1 carbonyl)-1-((2-(2,6-dioxopiper'}
{'row': 264, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 265, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-Amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8 diazab'}
{'row': 266, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 267, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 268, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 269, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 270, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 271, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 272, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 273, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 274, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 275, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 276, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 277, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 278, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 279, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 280, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 281, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 282, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 283, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 284, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 285, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 286, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 287, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 288, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 289, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 290, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 291, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 292, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 293, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 294, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 295, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 296, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 297, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 298, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 299, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 300, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 301, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 302, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 303, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 304, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 305, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 306, 'status': 404, 'DOI': '10.1038/s41467-022-34562-5', 'Compound_Name': 'A947', 'IUPAC_Name': '(2S,4R)-1-((2R)-2-(3-(4-((4-((1r,3r)-3-((4-(3-(3-amino-6-(2-hydroxyphenyl)pyridazin-4-yl)-3,8-diazab'}
{'row': 444, 'status': 404, 'DOI': '10.1021/acs.jmedchem.1c02179', 'Compound_Name': '10', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(2-((4-((2-Aminophenyl)carbamoyl)phenyl)amino)-2-oxoethoxy)ethoxy) acetamido)-3,'}
{'row': 445, 'status': 404, 'DOI': '10.1021/acs.jmedchem.1c02179', 'Compound_Name': '10', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(2-((4-((2-Aminophenyl)carbamoyl)phenyl)amino)-2-oxoethoxy)ethoxy) acetamido)-3,'}
{'row': 446, 'status': 404, 'DOI': '10.1021/acs.jmedchem.1c02179', 'Compound_Name': '10', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(2-(2-((4-((2-Aminophenyl)carbamoyl)phenyl)amino)-2-oxoethoxy)ethoxy) acetamido)-3,'}
{'row': 541, 'status': 404, 'DOI': '10.1038/s41591-019-0668-z', 'Compound_Name': 'DT2216', 'IUPAC_Name': '(2S,4R)-1-((S)-2-(7-(4-((R)-3-((4-(N-(4-(4-((4 -chloro-4,4-dimethyl-3,4,5,6-tetrahydro-[1,1 -bipheny'}
{'row': 564, 'status': 404, 'DOI': '10.1021/acs.jmedchem.1c01496', 'Compound_Name': 'OMZ1', 'IUPAC_Name': '(S)-13-((2S,4R)-4-Hydroxy-2-((4-(4-methylthiazol-5-yl)benzyl)carbamoyl)pyrrolidine-1-carbonyl)-15,15'}
{'row': 565, 'status': 404, 'DOI': '10.1021/acs.jmedchem.1c01496', 'Compound_Name': 'OMZ1', 'IUPAC_Name': '(S)-13-((2S,4R)-4-Hydroxy-2-((4-(4-methylthiazol-5-yl)benzyl)carbamoyl)pyrrolidine-1-carbonyl)-15,15'}
{'row': 566, 'status': 404, 'DOI': '10.1021/acs.jmedchem.1c01496', 'Compound_Name': 'OMZ1', 'IUPAC_Name': '(S)-13-((2S,4R)-4-Hydroxy-2-((4-(4-methylthiazol-5-yl)benzyl)carbamoyl)pyrrolidine-1-carbonyl)-15,15'}
{'row': 591, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00771', 'Compound_Name': 'NU223612', 'IUPAC_Name': '(2R)-N-(4-((1-(3-(2-(2-((2-(2,6-dioxopiperidin-3-yl)-1,3-dioxoisoindolin-4-yl)amino)ethoxy)ethoxy)pr'}
{'row': 592, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00771', 'Compound_Name': 'NU223612', 'IUPAC_Name': '(2R)-N-(4-((1-(3-(2-(2-((2-(2,6-dioxopiperidin-3-yl)-1,3-dioxoisoindolin-4-yl)amino)ethoxy)ethoxy)pr'}
{'row': 602, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6c', 'IUPAC_Name': '4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)-N-(2-(2,6-dioxopip'}
{'row': 603, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6c', 'IUPAC_Name': '4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)-N-(2-(2,6-dioxopip'}
{'row': 604, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6d', 'IUPAC_Name': '2-(4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)piperazin-1-yl)-'}
{'row': 605, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6d', 'IUPAC_Name': '2-(4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)piperazin-1-yl)-'}
{'row': 606, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6e', 'IUPAC_Name': '3-(4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)piperazin-1-yl)-'}
{'row': 607, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '6e', 'IUPAC_Name': '3-(4-(4-(3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)ureido)phenyl)piperazin-1-yl)-'}
{'row': 608, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7b', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((E)-3-(2-(2,6-dioxopiperidin-'}
{'row': 609, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7b', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((E)-3-(2-(2,6-dioxopiperidin-'}
{'row': 610, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7e', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-(2-((2-(2,6-dioxopiperidin-3-y'}
{'row': 611, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7e', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-(2-((2-(2,6-dioxopiperidin-3-y'}
{'row': 612, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7f', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}
{'row': 613, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '7f', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}
{'row': 614, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '8a', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}
{'row': 615, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '8a', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}
{'row': 616, 'status': 404, 'DOI': '10.1021/acs.jmedchem.2c00384', 'Compound_Name': '8b', 'IUPAC_Name': '3-Benzyl-1-((1r,4r)-4-((5-cyanopyridin-2-yl)amino)cyclohexyl)-1-(4-(4-((2-(2,6-dioxopiperidin-3-yl)-'}

In [9]:
output_path = os.path.join(data_dir, "260502_merged_protac_data_processed_cleaned_inchikey_3rd.csv")
merged_cleaned_protac.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_protac.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_3rd/260502_merged_protac_data_processed_cleaned_inchikey_3rd.csv
Shape: (694, 18)

### PubChem search

In [10]:
merged_cleaned_protac = pubchem_search(merged_cleaned_protac)

Rows missing Standard_InChIKey: 307 (139 unique (cname, iupac, smiles) triples)
  MATCH 'DT2216' via cname: CID=139331475, InChIKey=PXVFFBGSTYQHRO-REQIQPEASA-N
  MISS  'D3': skip: no usable name and no IUPAC/SMILES
  MISS  'D10': skip: no usable name and no IUPAC/SMILES
  MISS  'D12': skip: no usable name and no IUPAC/SMILES
  MISS  'D14': cname=0 results
  MISS  'D15': skip: no usable name and no IUPAC/SMILES
  MISS  'SJFα': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MATCH 'SJF-6690' via cname: CID=145748096, InChIKey=PCRYOGWRHSLIEZ-XZVMHGATSA-N
  MATCH 'SJF-6677' via cname: CID=145748084, InChIKey=LCBLIBYLVHDHMI-JCYIICMFSA-N
  MATCH 'SJF-0628' via cname: CID=146547699, InChIKey=MBCAVOCJJAQHHT-FGUOTCRGSA-N
  MISS  '15a': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MISS  '15b': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MATCH 'RC32' via cname: CID=156599864, InChIKey=XCSUEITWRRFFMN-LPIXFUNRSA-N
  MISS  'CRBN_1b': cname=0 results
  MISS  'CRBN_1e': cname=0 results
  MISS  'NP8': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MATCH 'dBET57' via cname: CID=118912822, InChIKey=CZRLOIDJCMKJHE-UXMRNZNESA-N
  MATCH 'A6' via SMILES: CID=166642468, InChIKey=FQLCLMHMOFLVSV-UHFFFAOYSA-N
  MATCH 'QC-01-175' via cname: CID=139593563, InChIKey=NWTCZTAQSRLSCP-UHFFFAOYSA-N
  MISS  'FMF-06-038': cname=0 results
  MISS  'FMF-06-049': cname=0 results
  MISS  'FMF-05-129-2': cname=0 results
  MISS  'FMF-06-066': cname=0 results
  MISS  '16': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MISS  '2': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MISS  '1': skip: no usable name and no IUPAC/SMILES
  MATCH 'JMC-137' via cname: CID=168275983, InChIKey=HWEFEZUTECUWNS-IIWOMYBWSA-N
  MATCH 'C004019' via cname: CID=164889480, InChIKey=IXTMPMLKABNFTQ-LLIFGLRNSA-N
  MISS  'A13': skip: no usable name and no IUPAC/SMILES
  MISS  'PROTAC-3': cname=not in synonyms (CID=135156947)
  MISS  '5': skip: no usable name and no IUPAC/SMILES
  MATCH 'TP1L' via cname: CID=169494290, InChIKey=TYEKCBCNQAFGHN-QSITVTTKSA-N
  MISS  'TPiL': cname=0 results
  MISS  'TC5L': cname=0 results
  MISS  'TC6L': cname=0 results
  MISS  'TC4L': cname=0 results
  MISS  'TC7L': cname=0 results
  MISS  'TP8L': cname=0 results
  MISS  'TC5P': cname=0 results
  MISS  'TC6P': cname=0 results
  MISS  'TC4P': cname=0 results
  MISS  'TC7P': cname=0 results
  MISS  'TC8P': cname=0 results
  MISS  'TC9P': cname=0 results
  MATCH 'RGC' via cname: CID=5327031, InChIKey=CXJZYPFMAUCFPK-UHEVRTMESA-N
  MISS  'iRGC': cname=0 results
  MATCH 'NR-V04' via cname: CID=166998154, InChIKey=GAZVCLAVEAXIQM-ZVXNWPGJSA-N
  MISS  '2c': skip: no usable name and no IUPAC/SMILES
  MATCH 'MZ1' via cname: CID=122201421, InChIKey=PTAMRJLIOCHJMQ-PYNGZGNASA-N
  MISS  'PRO-6 E': cname=0 results
  MISS  '11a': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MATCH 'd9A-2' via cname: CID=156726730, InChIKey=WMBSSRAFHKGIRA-UHFFFAOYSA-N
  MISS  'dTAG13': cname=0 results
  MISS  'dTAG7': cname=0 results
  MISS  'CRBN(BRAF)-24': cname=0 results
  MISS  '6': skip: no usable name and no IUPAC/SMILES
  MATCH 'ACBI2' via cname: CID=167738509, InChIKey=JBTHUOYYUUPUOZ-LIHPQFRDSA-N
  MISS  '21': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MATCH 'macroPROTAC-1' via cname: CID=145704688, InChIKey=GMEHQGWGMMKWAX-NIQMDXQVSA-N
  MISS  'Cpd 1': skip: no usable name and no IUPAC/SMILES
  MATCH 'dBET1' via cname: CID=91799313, InChIKey=LKEGXJXRNBALBV-PMCHYTPCSA-N
  MISS  'B1-10J': cname=0 results
  MISS  'B1-10P': cname=0 results
  MISS  'B2-12P': cname=0 results
  MATCH 'IR-1' via cname: CID=168316234, InChIKey=AWOLTJZICWTLFS-AHDGVXFFSA-N
  MISS  'RC-3': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MISS  'RC-2': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MATCH 'CP5V' via cname: CID=139600343, InChIKey=BQQILUVLGKHSNJ-NWRQRLFSSA-N
  MISS  'XR-4': cname=0 results
  MATCH 'iRucaparib-AP5' via cname: CID=138857954, InChIKey=CDKSZVJXSCKNQN-UHFFFAOYSA-N
  MATCH 'iRucaparib-AP6' via cname: CID=138857977, InChIKey=YHMDCINUVWULST-UHFFFAOYSA-N
  MATCH 'iVeliparib-AP6' via cname: CID=138857963, InChIKey=XLGCZZCLPNSQNH-YMURELKOSA-N
  MISS  '2': skip: no usable name and no IUPAC/SMILES
  MATCH 'KY02111' via cname: CID=8582409, InChIKey=LXFKEVQQSKQXPR-UHFFFAOYSA-N
  MATCH 'SIAIS361034' via cname: CID=156298253, InChIKey=FBBJZLPPVPILEL-UHFFFAOYSA-N
  MATCH 'A947' via cname: CID=139546336, InChIKey=QQVCUSPUMMUFTD-NCXNEFEISA-N
  MATCH 'A947' via cname: CID=139546336, InChIKey=QQVCUSPUMMUFTD-NCXNEFEISA-N
  MATCH 'DD-03-171' via cname: CID=138059681, InChIKey=QBPVFCNYKUENHU-UHFFFAOYSA-N
  MATCH 'Pomalidomide' via cname: CID=134780, InChIKey=UVSMNLNDYGZFPF-UHFFFAOYSA-N
  MATCH 'CC220' via cname: CID=67335295, InChIKey=IXZOHGPZAQLIBH-NRFANRHFSA-N
  MISS  'PS-6': skip: no usable name and no IUPAC/SMILES
  MATCH 'QC-01–175' via cname: CID=139593563, InChIKey=NWTCZTAQSRLSCP-UHFFFAOYSA-N
  MATCH 'MD13' via cname: CID=163342432, InChIKey=HAHDZDUOFHMMEA-UHFFFAOYSA-N
  MISS  'MD9': skip: no usable name and no IUPAC/SMILES
  MATCH '10' via SMILES: CID=166635273, InChIKey=LDFNYUSMNVVOAO-FHRXIHKVSA-N
  MATCH 'dBET6' via cname: CID=121427831, InChIKey=JGQPZPLJOBHHBK-UFXYQILXSA-N
  MATCH 'dBET23' via cname: CID=124190790, InChIKey=ZIHIUFZFPMILIG-XLTVJXRZSA-N
  MATCH 'dBET70' via cname: CID=132427802, InChIKey=VDRKZYYQEGSLIS-XLTVJXRZSA-N
  MATCH 'dBET57' via cname: CID=118912822, InChIKey=CZRLOIDJCMKJHE-UXMRNZNESA-N
  MATCH 'ZXH-3-26' via cname: CID=132427808, InChIKey=OTKOFICOCDRNDA-PMCHYTPCSA-N
  MISS  '13c': cname=0 results
  MISS  'Comp-K': cname=0 results
  MISS  'Comp-L': cname=0 results
  MISS  'Comp-M': cname=0 results
  MISS  '7': skip: no usable name and no IUPAC/SMILES
  MISS  '11': skip: no usable name and no IUPAC/SMILES
  MATCH 'DT2216' via cname: CID=139331475, InChIKey=PXVFFBGSTYQHRO-REQIQPEASA-N
  MATCH 'VZ185' via cname: CID=138454768, InChIKey=ZAGCLFXBHOXXEN-JPTLTNPLSA-N
  MATCH 'dBRD9' via cname: CID=135397681, InChIKey=AIOCFZJGGGEWDK-UHFFFAOYSA-N
  MISS  'DDa-1': cname=0 results
  MISS  'DBt-5': cname=0 results
  MISS  'DBt-10': skip: no usable name and no IUPAC/SMILES
  MISS  'CDa-1': cname=0 results
  MATCH 'PROTAC 3' via cname: CID=135156947, InChIKey=NICKHWYZMNLEPJ-TZSMONEZSA-N
  MATCH 'AU-15330' via cname: CID=156168451, InChIKey=HDCCMCFIGHIDJR-TUDDPRDOSA-N
  MISS  '3': skip: no usable name and no IUPAC/SMILES
  MISS  '008': skip: no usable name and no IUPAC/SMILES
  MISS  '039': skip: no usable name and no IUPAC/SMILES
  MATCH 'MZ1' via cname: CID=122201421, InChIKey=PTAMRJLIOCHJMQ-PYNGZGNASA-N
  MISS  'OMZ1': cname=0 results; IUPAC=0 results, SMILES=no SMILES
  MATCH 'ARV-771' via cname: CID=126619980, InChIKey=PQOGZKGXGLHDGS-QQRWPDCKSA-N
  MATCH 'KH-103' via cname: CID=172432000, InChIKey=JCGJSWHANIFQTH-FJOMATKGSA-N
  MATCH 'NU223612' via cname: CID=166176927, InChIKey=PLYOHMQINGIYDN-LVMIGYEDSA-N
  MISS  '13a': cname=0 results
  MISS  '13b': skip: no usable name and no IUPAC/SMILES
  MISS  '13d': cname=0 results
  MISS  '14': skip: no usable name and no IUPAC/SMILES
  MATCH 'UBX-382' via cname: CID=166545675, InChIKey=WIAKHDZSMZDZQL-UHFFFAOYSA-N
  MATCH '6c' via SMILES: CID=168296465, InChIKey=GZGWGZGQYMUIEA-UHFFFAOYSA-N
  MATCH '6d' via SMILES: CID=168280695, InChIKey=RAQFFJNNGHFOJQ-UHFFFAOYSA-N
  MATCH '6e' via SMILES: CID=168291380, InChIKey=TXTOISHPMQZJTH-UHFFFAOYSA-N
  MATCH '7b' via SMILES: CID=168273780, InChIKey=AXXVVAVFAZXQRT-ODCIPOBUSA-N
  MATCH '7e' via SMILES: CID=168279854, InChIKey=BASKATKGOOUNTP-UHFFFAOYSA-N
  MATCH '7e' via SMILES: CID=168279854, InChIKey=BASKATKGOOUNTP-UHFFFAOYSA-N
  MATCH '7f' via IUPAC: CID=164887577, InChIKey=XTFJBIUTOVUAPR-UHFFFAOYSA-N
  MATCH '8a' via SMILES: CID=168290140, InChIKey=IEQQOSUYADIJKS-UHFFFAOYSA-N
  MATCH '8b' via SMILES: CID=168281662, InChIKey=BZWXDODDFPHMGW-UHFFFAOYSA-N
  MISS  'BTR2004': cname=0 results
  MISS  '34 (CST651)': cname=0 results
  MISS  'FS-ARV-825': cname=0 results
  MATCH 'ARV-825' via cname: CID=92044400, InChIKey=RWLOGRLTDKDANT-TYIYNAFKSA-N
  MISS  'KTX-335': cname=0 results
  MISS  'KTX-652': cname=0 results
  MISS  'KTX-978': cname=0 results
  MATCH 'XL01126' via cname: CID=165412689, InChIKey=HKSBXNVKPFTBIG-WUEKOBJSSA-N
  MISS  'XL01134': cname=0 results
  MISS  'WJ213-14': cname=0 results
  MISS  'WJ112-14': cname=0 results
  MISS  'WJ204-12': cname=0 results

--- PubChem Results ---
Matched triples: 59/139
Standard_InChIKey filled: 169
IUPAC_Name filled: 87
SMILES filled: 148
Standard_InChIKey still missing: 138

In [11]:
output_path = os.path.join(data_dir, "260502_merged_protac_data_processed_cleaned_inchikey_pubchem_3rd.csv")
merged_cleaned_protac.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_protac.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_3rd/260502_merged_protac_data_processed_cleaned_inchikey_pubchem_3rd.csv
Shape: (694, 19)

### Add connectivity_key

In [12]:
merged_cleaned_protac = add_connectivity_key(merged_cleaned_protac)

In [13]:
merged_cleaned_protac

,DOI,source,Compound_Name,IUPAC_Name,SMILES,SMILES_Source,Degradation_Target,Recruiter,Assay,Cell_Line,DC50,DC50_units,DC50_h,Dmax,Dmax_h,Dmax_conc,Standard_InChIKey,Standard_InChIKey_Source,IUPAC_Name_Source,Connectivity_Key
0,10.1021/acscentsci.0c00411,supplementary_oc0c00411_si_001.md,LC-2,"(2S,4R)-1-((S)-2-(3-(3-((S)-2-(((7-(8-chlorona...",ClC=1C=CC=C2C=CC=C(C12)N1CC=2N=C(N=C(C2CC1)N1C...,OPSIN,KRASG12C,VHL,immunoblotting,NCI-H2030,590.0 ± 200.0,nM,24,~80,24,2.5 μM,ZCGQZLKPUVGCBQ-HLMPTVQRSA-N,OPSIN,<NA>,ZCGQZLKPUVGCBQ
1,10.1021/acscentsci.0c00411,supplementary_oc0c00411_si_001.md,LC-2,"(2S,4R)-1-((S)-2-(3-(3-((S)-2-(((7-(8-chlorona...",ClC=1C=CC=C2C=CC=C(C12)N1CC=2N=C(N=C(C2CC1)N1C...,OPSIN,KRASG12C,VHL,immunoblotting,MIA PaCa-2,320.0 ± 80.0,nM,24,~75,24,NaN,ZCGQZLKPUVGCBQ-HLMPTVQRSA-N,OPSIN,<NA>,ZCGQZLKPUVGCBQ
2,10.1021/acscentsci.0c00411,supplementary_oc0c00411_si_001.md,LC-2,"(2S,4R)-1-((S)-2-(3-(3-((S)-2-(((7-(8-chlorona...",ClC=1C=CC=C2C=CC=C(C12)N1CC=2N=C(N=C(C2CC1)N1C...,OPSIN,KRASG12C,VHL,immunoblotting,SW1573,760.0 ± 300.0,nM,24,~90,24,NaN,ZCGQZLKPUVGCBQ-HLMPTVQRSA-N,OPSIN,<NA>,ZCGQZLKPUVGCBQ
3,10.1021/acscentsci.0c00411,supplementary_oc0c00411_si_001.md,LC-2,"(2S,4R)-1-((S)-2-(3-(3-((S)-2-(((7-(8-chlorona...",ClC=1C=CC=C2C=CC=C(C12)N1CC=2N=C(N=C(C2CC1)N1C...,OPSIN,KRASG12C,VHL,immunoblotting,NCI-H23,250.0 ± 80.0,nM,24,~90,24,NaN,ZCGQZLKPUVGCBQ-HLMPTVQRSA-N,OPSIN,<NA>,ZCGQZLKPUVGCBQ
4,10.1021/acscentsci.0c00411,supplementary_oc0c00411_si_001.md,LC-2,"(2S,4R)-1-((S)-2-(3-(3-((S)-2-(((7-(8-chlorona...",ClC=1C=CC=C2C=CC=C(C12)N1CC=2N=C(N=C(C2CC1)N1C...,OPSIN,KRASG12C,VHL,immunoblotting,NCI-H358,520.0 ± 300.0,nM,24,~40,24,NaN,ZCGQZLKPUVGCBQ-HLMPTVQRSA-N,OPSIN,<NA>,ZCGQZLKPUVGCBQ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
689,10.1039/d3sc04629j,main_text,WJ112-14,NaN,NaN,<NA>,PI3Kβ (p110β),CRBN,PRM targeted proteomics,MCF7,NaN,NaN,NaN,0,6,1 μM,<NA>,<NA>,<NA>,<NA>
690,10.1039/d3sc04629j,main_text,WJ204-12,NaN,NaN,<NA>,PI3Kβ (p110β),CRBN,PRM targeted proteomics,MCF7,NaN,NaN,NaN,~50,6,100 nM,<NA>,<NA>,<NA>,<NA>
691,10.1038/s41467-019-11429-w,supplementary_41467_2019_11429_MOESM1_ESM.md,DGY-03-081,"N2-((S)-1-cyclohexyl-2-((S)-1-((1S,3aR,6aS)-1-...",C1(CCCCC1)[C@@H](C(=O)N[C@H](C(=O)N1[C@@H]([C@...,OPSIN,HCV NS3,CRBN,Flow cytometry of NS3-eGFP-2A-mCherry reporter...,Flp-In T-REx 293,668.5,nM,4 h,NaN,NaN,NaN,KJEYLCKKOBCAHO-KSESKIPOSA-N,OPSIN,<NA>,KJEYLCKKOBCAHO
692,10.1038/s41467-019-11429-w,supplementary_41467_2019_11429_MOESM1_ESM.md,DGY-04-035,"N2-((S)-1-cyclohexyl-2-((S)-1-((1S,3aR,6aS)-1-...",C1(CCCCC1)[C@@H](C(=O)N[C@H](C(=O)N1[C@@H]([C@...,OPSIN,HCV NS3,CRBN,Flow cytometry of NS3-eGFP-2A-mCherry reporter...,Flp-In T-REx 293,488.6,nM,4 h,NaN,NaN,NaN,NPXHZAXKZQRUGW-KSESKIPOSA-N,OPSIN,<NA>,NPXHZAXKZQRUGW
693,10.1038/s41467-019-11429-w,supplementary_41467_2019_11429_MOESM1_ESM.md,DGY-08-097,"N2-((S)-1-cyclohexyl-2-((S)-1-((1S,3aR,6aS)-1-...",C1(CCCCC1)[C@@H](C(=O)N[C@H](C(=O)N1[C@@H]([C@...,OPSIN,HCV NS3,CRBN,Flow cytometry of NS3-eGFP-2A-mCherry reporter...,Flp-In T-REx 293,50,nM,4 h,NaN,NaN,NaN,YZNSNVPSBDWZBQ-LNWDVATRSA-N,OPSIN,<NA>,YZNSNVPSBDWZBQ

In [14]:
output_path = os.path.join(data_dir, "260502_merged_protac_data_processed_cleaned_inchikey_pubchem_ck_3rd.csv")
merged_cleaned_protac.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_protac.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260502_protac_data_all_reps/data_3rd/260502_merged_protac_data_processed_cleaned_inchikey_pubchem_ck_3rd.csv
Shape: (694, 20)

# Porcess Molecular Glues Extracted Data

In [2]:
import pandas as pd
import os

glue_path = '/Users/yaochenr/project/molecular_glue_extractor/output/results/260504_1725/data_processed.csv'
merged_glues = pd.read_csv(glue_path)
merged_glues.head()

,DOI,source,Compound_Name,IUPAC_Name,SMILES,Degradation_Target,Recruiter,Assay,Cell_Line,DC50,DC50_units,DC50_h,Dmax,Dmax_h,Dmax_conc
0,10.1038/ncomms15398,main_text,lenalidomide,NaN,NaN,ZFP91,CRBN (CRL4CRBN),pSILAC mass spectrometry (multi time point; an...,HEK293T,NaN,NaN,NaN,NaN,NaN,NaN
1,10.1038/ncomms15398,main_text,lenalidomide,NaN,NaN,ZFP91,CRBN (CRL4CRBN),pSILAC mass spectrometry (single time point),Hct116,NaN,NaN,NaN,NaN,NaN,NaN
2,10.1038/ncomms15398,main_text,lenalidomide,NaN,NaN,CSNK1A1,CRBN (CRL4CRBN),pSILAC mass spectrometry (multi time point; an...,HEK293T,NaN,NaN,NaN,NaN,NaN,NaN
3,10.1038/ncomms15398,main_text,lenalidomide,NaN,NaN,CSNK1A1,CRBN (CRL4CRBN),pSILAC mass spectrometry (single time point),Hct116,NaN,NaN,NaN,NaN,NaN,NaN
4,10.1038/ncomms15398,main_text,lenalidomide,NaN,NaN,ZFP91,CRBN (CRL4CRBN),Western blot,MM.1S,NaN,NaN,NaN,NaN,NaN,NaN

### Remove rows where DC50 & Dmax are both empty

In [3]:
merged_cleaned_glues = remove_empty_dc50_dmax(merged_glues)

Removed 122 rows where both DC50 and Dmax are empty
Shape: 401 -> 279

In [4]:
data_dir_glues = "/Users/yaochenr/project/molecular_glue_extractor/output/results/260504-glue-data-all-rep/data_3rd"
os.makedirs(data_dir_glues, exist_ok=True)
output_merged = os.path.join(data_dir_glues, "260504_merged_glue_data_processed_cleaned_3rd.csv")
merged_cleaned_glues.to_csv(output_merged, index=False)
print(f"Saved cleaned merged data to: {output_merged}")
print(f"Shape: {merged_cleaned_glues.shape}")

Saved cleaned merged data to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260504-glue-data-all-rep/data_3rd/260504_merged_glue_data_processed_cleaned_3rd.csv
Shape: (279, 15)

## Add Standard InChIKey via OPSIN

In [5]:
merged_cleaned_glues = add_inchikey_opsin(merged_cleaned_glues)

Rows with SMILES from paper: 32
Processed 250/279 rows...

Done! Success: 208, Failed: 13, Skipped (no IUPAC): 58
Standard_InChIKey filled: 208
SMILES from PAPER: 32
SMILES from OPSIN: 178
SMILES still missing: 69

--- Failed rows ---
{'row': 59, 'status': 404, 'DOI': '10.1038/s41467-025-58431-z', 'Compound_Name': '7', 'IUPAC_Name': "3-(6'-oxo-4-phenoxy-6',8'-dihydro-2'H,7'H-spiro[cyclohexane-1,3' furo[2,3-e]isoindol]-7'-yl)piperidi"}
{'row': 61, 'status': 404, 'DOI': '10.1038/s41467-025-58431-z', 'Compound_Name': '9', 'IUPAC_Name': "3-(1-benzyl-6'-oxo-6',8'-dihydro-2'H,7'H-spiro[azepane-4,3' furo[2,3-e]isoindol]-7'-yl)piperidine-2,"}
{'row': 64, 'status': 404, 'DOI': '10.1038/s41467-025-58431-z', 'Compound_Name': '12', 'IUPAC_Name': "3-(1'-benzyl-3',3'-difluoro-6-oxo-6,8-dihydro-2H,7H-spiro[furo[2,3 e]isoindole-3,4'-piperidin]-7-yl)"}
{'row': 65, 'status': 404, 'DOI': '10.1038/s41467-025-58431-z', 'Compound_Name': '13', 'IUPAC_Name': "3-(1'-(cyclohexylmethyl)-6-oxo-6,8-dihydro-2H,7H-spiro[furo[2,3 e]isoindole-3,4'-piperidin]-7-yl)pip"}
{'row': 66, 'status': 404, 'DOI': '10.1038/s41467-025-58431-z', 'Compound_Name': '14', 'IUPAC_Name': "3-(6-oxo-1'-(pyridin-2-ylmethyl)-6,8-dihydro-2H,7H-spiro[furo[2,3 e]isoindole-3,4'-piperidin]-7-yl)p"}
{'row': 67, 'status': 404, 'DOI': '10.1038/s41467-025-58431-z', 'Compound_Name': '15', 'IUPAC_Name': "3-(6-oxo-1'-(thiophen-3-ylmethyl)-6,8-dihydro-2H,7H-spiro[furo[2,3 e]isoindole-3,4'-piperidin]-7-yl)"}
{'row': 83, 'status': 404, 'DOI': '10.1186/s13045-024-01592-z', 'Compound_Name': 'MGD-28', 'IUPAC_Name': '4 - (4 - (4 - (2 - (2, 6 - oxygen generation of piperidine 2-3 - base) - 3 - methyl - 1 - - 1, 2, 3,'}
{'row': 84, 'status': 404, 'DOI': '10.1186/s13045-024-01592-z', 'Compound_Name': 'MGD-28', 'IUPAC_Name': '4 - (4 - (4 - (2 - (2, 6 - oxygen generation of piperidine 2-3 - base) - 3 - methyl - 1 - - 1, 2, 3,'}
{'row': 85, 'status': 404, 'DOI': '10.1186/s13045-024-01592-z', 'Compound_Name': 'MGD-28', 'IUPAC_Name': '4 - (4 - (4 - (2 - (2, 6 - oxygen generation of piperidine 2-3 - base) - 3 - methyl - 1 - - 1, 2, 3,'}
{'row': 86, 'status': 404, 'DOI': '10.1186/s13045-024-01592-z', 'Compound_Name': 'MGD-28', 'IUPAC_Name': '4 - (4 - (4 - (2 - (2, 6 - oxygen generation of piperidine 2-3 - base) - 3 - methyl - 1 - - 1, 2, 3,'}
{'row': 109, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS02', 'IUPAC_Name': 'Not provided explicitly'}
{'row': 125, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS47', 'IUPAC_Name': '(S)-N2-((S)-N-(4-(hydroxymethyl)phenyl)-2-((9-isopropyl-6-((4-(pyridin-2-yl)benzyl)amino)-9H-purin-2'}
{'row': 134, 'status': 404, 'DOI': '10.1038/s41589-023-01409-z', 'Compound_Name': 'DS64', 'IUPAC_Name': '(R)-2-((6-((4,5-difluoro-1H-benzo[d]imidazol-2-yl)methyl)amino)-9-isopropyl-9H-purin-2-yl)amino)buta'}

In [6]:
output_path = os.path.join(data_dir_glues, "260504_merged_glue_data_processed_cleaned_inchikey_3rd.csv")
merged_cleaned_glues.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_glues.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260504-glue-data-all-rep/data_3rd/260504_merged_glue_data_processed_cleaned_inchikey_3rd.csv
Shape: (279, 18)

## PubChem Search

In [7]:
merged_cleaned_glues = pubchem_search(merged_cleaned_glues)

Rows missing Standard_InChIKey: 71 (45 unique (cname, iupac, smiles) triples)
  MISS  'MG-Lin1': cname=0 results
  MATCH 'lenalidomide' via cname: CID=216326, InChIKey=GOTYRUGSSMKFNF-UHFFFAOYSA-N
  MATCH 'dBET57' via cname: CID=118912822, InChIKey=CZRLOIDJCMKJHE-UXMRNZNESA-N
  MATCH 'A6' via SMILES: CID=166642468, InChIKey=FQLCLMHMOFLVSV-UHFFFAOYSA-N
  MISS  '13-7': skip: no usable name and no IUPAC/SMILES
  MATCH 'DKY709' via cname: CID=137519326, InChIKey=OMISHRJQMYQPMG-UHFFFAOYSA-N
  MISS  '7': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MISS  '9': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MISS  '12': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MISS  '13': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MISS  '14': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MISS  '15': cname unusable; IUPAC=0 results, SMILES=no SMILES
  MISS  'iDeg-6': cname=0 results
  MATCH 'Pomalidomide' via cname: CID=134780, InChIKey=UVSMNLNDYGZFPF-UHFFFAOYSA-N
  MATCH 'Lenalidomide' via cname: CID=216326, InChIKey=GOTYRUGSSMKFNF-UHFFFAOYSA-N
  MATCH 'MGD-28' via cname: CID=172871692, InChIKey=JICHBFQDRLGJTM-UHFFFAOYSA-N
  MATCH 'PT-179' via cname: CID=163294079, InChIKey=CCCSRHUSXCBFJZ-UHFFFAOYSA-N
  MATCH 'pomalidomide' via cname: CID=134780, InChIKey=UVSMNLNDYGZFPF-UHFFFAOYSA-N
  MATCH 'SR-4835' via cname: CID=139600338, InChIKey=FSELUFUYNUNZKD-UHFFFAOYSA-N
  MISS  'CU-0906': cname=0 results
  MISS  'VNPP433-3β': cname=0 results
  MISS  'LC-04–075': cname=0 results
  MISS  'LC-04–087': cname=0 results
  MISS  'LC-04–081': cname=0 results
  MISS  'LC-04–077': cname=0 results
  MISS  'LC-04–155': cname=0 results
  MISS  'LC-04–162': cname=0 results
  MISS  'CR8': cname=0 results
  MATCH 'DS02' via cname: CID=168499469, InChIKey=KLBKESYFUKKKSS-LJQANCHMSA-N
  MATCH 'DS47' via cname: CID=168499490, InChIKey=LVVKHGPMCAECNF-CONSDPRKSA-N
  MATCH 'DS64' via cname: CID=168499496, InChIKey=DCTODZNTFHJKGP-LLVKDONJSA-N
  MISS  '21195': skip: no usable name and no IUPAC/SMILES
  MISS  '919278': skip: no usable name and no IUPAC/SMILES
  MATCH 'dCeMM2' via cname: CID=5286209, InChIKey=VFWVTIHYVUKNGR-UHFFFAOYSA-N
  MATCH 'dCeMM4' via cname: CID=53546112, InChIKey=BPWZJVKIVHVVHP-UHFFFAOYSA-N
  MATCH 'HQ461' via cname: CID=49677967, InChIKey=QMRBCNQCRMTXBE-UHFFFAOYSA-N
  MISS  'Z11': cname=0 results
  MISS  'Z12': cname=0 results
  MISS  'Z10': cname=0 results
  MISS  'DS_CR8': cname=0 results
  MISS  '5': skip: no usable name and no IUPAC/SMILES
  MISS  '4': skip: no usable name and no IUPAC/SMILES
  MISS  '13': skip: no usable name and no IUPAC/SMILES
  MATCH 'SJ3149' via cname: CID=168511381, InChIKey=AJUZTJBGJWQZFW-UHFFFAOYSA-N
  MATCH 'CC-90009' via cname: CID=118647211, InChIKey=PWBHUSLMHZLGRN-UHFFFAOYSA-N

--- PubChem Results ---
Matched triples: 18/45
Standard_InChIKey filled: 40
IUPAC_Name filled: 33
SMILES filled: 38
Standard_InChIKey still missing: 31

In [8]:
output_path = os.path.join(data_dir_glues, "260504_merged_glue_data_processed_cleaned_inchikey_pubchem_3rd.csv")
merged_cleaned_glues.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_glues.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260504-glue-data-all-rep/data_3rd/260504_merged_glue_data_processed_cleaned_inchikey_pubchem_3rd.csv
Shape: (279, 19)

## Add connectivity_key

In [9]:
merged_cleaned_glues = add_connectivity_key(merged_cleaned_glues)

In [10]:
merged_cleaned_glues[['Compound_Name', 'Standard_InChIKey', 'Connectivity_Key']]

    Compound_Name            Standard_InChIKey Connectivity_Key
0         MG-Lin1                         <NA>             <NA>
1              5a  MSHTVRYXGFREAN-UHFFFAOYSA-N   MSHTVRYXGFREAN
2              7d  QRQMHYISDDHZBY-UHFFFAOYSA-N   QRQMHYISDDHZBY
3              7f  NSEUGMATEWSNTO-UHFFFAOYSA-N   NSEUGMATEWSNTO
4    lenalidomide  GOTYRUGSSMKFNF-UHFFFAOYSA-N   GOTYRUGSSMKFNF
..            ...                          ...              ...
274     CCT373566  GSGDUDAFETZSPM-IATAILRESA-N   GSGDUDAFETZSPM
275     CCT373567  GSGDUDAFETZSPM-DHZVRSILSA-N   GSGDUDAFETZSPM
276     CCT373566  GSGDUDAFETZSPM-IATAILRESA-N   GSGDUDAFETZSPM
277     CCT373567  GSGDUDAFETZSPM-DHZVRSILSA-N   GSGDUDAFETZSPM
278     CCT373566  GSGDUDAFETZSPM-IATAILRESA-N   GSGDUDAFETZSPM

[279 rows x 3 columns]

In [11]:
output_path = os.path.join(data_dir_glues, "260504_merged_glue_data_processed_cleaned_inchikey_pubchem_ck_3rd.csv")
merged_cleaned_glues.to_csv(output_path, index=False)
print(f"Saved to: {output_path}")
print(f"Shape: {merged_cleaned_glues.shape}")

Saved to: /Users/yaochenr/project/molecular_glue_extractor/output/results/260504-glue-data-all-rep/data_3rd/260504_merged_glue_data_processed_cleaned_inchikey_pubchem_ck_3rd.csv
Shape: (279, 20)